# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['USER_INTERFACE\\gui.py'],
    pathex=[],
    binaries=[],
    datas=[('DATA', 'DATA'), ('AUTOMATION', 'AUTOMATION'), ('FUNCTION', 'FUNCTION'), ('BRAIN', 'BRAIN'), ('MAIN/mixkit-high-tech-bleep-2521.wav', 'MAIN') ],
    hiddenimports=[
        'pyautogui',
        'PyScreeze',
        'pyscreeze',
        'pymsgbox',
        'pytweening',
        'pygetwindow',
        'sumy',
        'sumy.parsers',
        'sumy.summarizers',
        'sumy.summarizers.lsa',
        'sumy.summarizers.text_rank',
        'sumy.parsers.plaintext',
        'sumy.nlp.tokenizers',
        'sumy.nlp',
        'PyQt5',
        'playsound',
        'pywhatkit',
        'psutil',
        'speech_recognition',
        'mtranslate',
        'selenium',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
