# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 363)
        MainWindow.setStyleSheet("background-color: #0a0f1b;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(20, -1, 20, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.innerLayout = QtWidgets.QGridLayout()
        self.innerLayout.setObjectName("innerLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.innerLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.innerLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.arc_react_image_background = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arc_react_image_background.sizePolicy().hasHeightForWidth())
        self.arc_react_image_background.setSizePolicy(sizePolicy)
        self.arc_react_image_background.setMinimumSize(QtCore.QSize(200, 200))
        self.arc_react_image_background.setMaximumSize(QtCore.QSize(200, 200))
        self.arc_react_image_background.setScaledContents(True)
        self.arc_react_image_background.setObjectName("arc_react_image_background")
        self.innerLayout.addWidget(self.arc_react_image_background, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.innerLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.innerLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.innerLayout, 0, 0, 9, 2)
        self.footerMainLayout = QtWidgets.QVBoxLayout()
        self.footerMainLayout.setObjectName("footerMainLayout")
        self.footer_above_line = QtWidgets.QFrame(self.centralwidget)
        self.footer_above_line.setStyleSheet("background-color: rgba(34, 211, 238, 0.3);")
        self.footer_above_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.footer_above_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.footer_above_line.setObjectName("footer_above_line")
        self.footerMainLayout.addWidget(self.footer_above_line)
        self.Operational_footer_1 = QtWidgets.QHBoxLayout()
        self.Operational_footer_1.setContentsMargins(10, -1, 10, -1)
        self.Operational_footer_1.setSpacing(0)
        self.Operational_footer_1.setObjectName("Operational_footer_1")
        self.StatusRow1 = QtWidgets.QHBoxLayout()
        self.StatusRow1.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow1.setSpacing(6)
        self.StatusRow1.setObjectName("StatusRow1")
        self.StatusLabelLayout1 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout1.setObjectName("StatusLabelLayout1")
        self.Operation_1 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_1.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_1.setObjectName("Operation_1")
        self.StatusLabelLayout1.addWidget(self.Operation_1)
        self.Title_1 = QtWidgets.QLabel(self.centralwidget)
        self.Title_1.setStyleSheet("color: gray;")
        self.Title_1.setObjectName("Title_1")
        self.StatusLabelLayout1.addWidget(self.Title_1)
        self.StatusRow1.addLayout(self.StatusLabelLayout1)
        self.Dot_Operation_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_1.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_1.setSizePolicy(sizePolicy)
        self.Dot_Operation_1.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_1.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_1.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #4ade80;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        icon = QtGui.QIcon()
        self.Dot_Operation_1.setIcon(icon)
        self.Dot_Operation_1.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_1.setObjectName("Dot_Operation_1")
        self.StatusRow1.addWidget(self.Dot_Operation_1, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow1)
        self.StatusRow2 = QtWidgets.QHBoxLayout()
        self.StatusRow2.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow2.setSpacing(6)
        self.StatusRow2.setObjectName("StatusRow2")
        self.StatusLabelLayout2 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout2.setObjectName("StatusLabelLayout2")
        self.Operation_2 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_2.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_2.setObjectName("Operation_2")
        self.StatusLabelLayout2.addWidget(self.Operation_2)
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setStyleSheet("color: gray;")
        self.Title_2.setObjectName("Title_2")
        self.StatusLabelLayout2.addWidget(self.Title_2)
        self.StatusRow2.addLayout(self.StatusLabelLayout2)
        self.Dot_Operation_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_2.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_2.setSizePolicy(sizePolicy)
        self.Dot_Operation_2.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_2.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_2.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #22d3ee;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        self.Dot_Operation_2.setIcon(icon)
        self.Dot_Operation_2.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_2.setObjectName("Dot_Operation_2")
        self.StatusRow2.addWidget(self.Dot_Operation_2, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow2)
        self.StatusRow3 = QtWidgets.QHBoxLayout()
        self.StatusRow3.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow3.setSpacing(6)
        self.StatusRow3.setObjectName("StatusRow3")
        self.StatusLabelLayout3 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout3.setObjectName("StatusLabelLayout3")
        self.Operation_3 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_3.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_3.setObjectName("Operation_3")
        self.StatusLabelLayout3.addWidget(self.Operation_3)
        self.Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.Title_3.setStyleSheet("color: gray;")
        self.Title_3.setObjectName("Title_3")
        self.StatusLabelLayout3.addWidget(self.Title_3)
        self.StatusRow3.addLayout(self.StatusLabelLayout3)
        self.Dot_Operation_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_3.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_3.setSizePolicy(sizePolicy)
        self.Dot_Operation_3.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_3.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_3.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #60a5fa;\n"
"    }\n"
"   ")
        self.Dot_Operation_3.setIcon(icon)
        self.Dot_Operation_3.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_3.setObjectName("Dot_Operation_3")
        self.StatusRow3.addWidget(self.Dot_Operation_3, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow3)
        self.StatusRow4 = QtWidgets.QHBoxLayout()
        self.StatusRow4.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow4.setSpacing(6)
        self.StatusRow4.setObjectName("StatusRow4")
        self.StatusLabelLayout4 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout4.setObjectName("StatusLabelLayout4")
        self.Operation_4 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_4.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_4.setObjectName("Operation_4")
        self.StatusLabelLayout4.addWidget(self.Operation_4)
        self.Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.Title_4.setStyleSheet("color: gray;")
        self.Title_4.setObjectName("Title_4")
        self.StatusLabelLayout4.addWidget(self.Title_4)
        self.StatusRow4.addLayout(self.StatusLabelLayout4)
        self.Dot_Operation_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_4.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_4.setSizePolicy(sizePolicy)
        self.Dot_Operation_4.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_4.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_4.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #818cf8;\n"
"    }\n"
"   ")
        self.Dot_Operation_4.setIcon(icon)
        self.Dot_Operation_4.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_4.setObjectName("Dot_Operation_4")
        self.StatusRow4.addWidget(self.Dot_Operation_4, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow4)
        self.StatusRow5 = QtWidgets.QHBoxLayout()
        self.StatusRow5.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow5.setSpacing(6)
        self.StatusRow5.setObjectName("StatusRow5")
        self.StatusLabelLayout5 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout5.setObjectName("StatusLabelLayout5")
        self.Operation_5 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_5.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_5.setObjectName("Operation_5")
        self.StatusLabelLayout5.addWidget(self.Operation_5)
        self.Title_5 = QtWidgets.QLabel(self.centralwidget)
        self.Title_5.setStyleSheet("color: gray;")
        self.Title_5.setObjectName("Title_5")
        self.StatusLabelLayout5.addWidget(self.Title_5)
        self.StatusRow5.addLayout(self.StatusLabelLayout5)
        self.Dot_Operation_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_5.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_5.setSizePolicy(sizePolicy)
        self.Dot_Operation_5.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_5.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_5.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #10b981;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        self.Dot_Operation_5.setIcon(icon)
        self.Dot_Operation_5.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_5.setObjectName("Dot_Operation_5")
        self.StatusRow5.addWidget(self.Dot_Operation_5, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow5)
        self.StatusRow6 = QtWidgets.QHBoxLayout()
        self.StatusRow6.setContentsMargins(-1, -1, 15, -1)
        self.StatusRow6.setSpacing(6)
        self.StatusRow6.setObjectName("StatusRow6")
        self.StatusLabelLayout6 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout6.setObjectName("StatusLabelLayout6")
        self.Operation_6 = QtWidgets.QLabel(self.centralwidget)
        self.Operation_6.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_6.setObjectName("Operation_6")
        self.StatusLabelLayout6.addWidget(self.Operation_6)
        self.Title_6 = QtWidgets.QLabel(self.centralwidget)
        self.Title_6.setStyleSheet("color: gray;")
        self.Title_6.setObjectName("Title_6")
        self.StatusLabelLayout6.addWidget(self.Title_6)
        self.StatusRow6.addLayout(self.StatusLabelLayout6)
        self.Dot_Operation_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dot_Operation_6.sizePolicy().hasHeightForWidth())
        self.Dot_Operation_6.setSizePolicy(sizePolicy)
        self.Dot_Operation_6.setMinimumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_6.setMaximumSize(QtCore.QSize(8, 8))
        self.Dot_Operation_6.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #facc15;\n"
"    }\n"
"   ")
        self.Dot_Operation_6.setIcon(icon)
        self.Dot_Operation_6.setIconSize(QtCore.QSize(30, 30))
        self.Dot_Operation_6.setObjectName("Dot_Operation_6")
        self.StatusRow6.addWidget(self.Dot_Operation_6, 0, QtCore.Qt.AlignLeft)
        self.Operational_footer_1.addLayout(self.StatusRow6)
        self.footerMainLayout.addLayout(self.Operational_footer_1)
        self.footer_below_line = QtWidgets.QFrame(self.centralwidget)
        self.footer_below_line.setStyleSheet("background-color: rgba(34, 211, 238, 0.3);")
        self.footer_below_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.footer_below_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.footer_below_line.setObjectName("footer_below_line")
        self.footerMainLayout.addWidget(self.footer_below_line)
        self.bottom_footer_2 = QtWidgets.QHBoxLayout()
        self.bottom_footer_2.setContentsMargins(10, -1, 10, 0)
        self.bottom_footer_2.setObjectName("bottom_footer_2")
        self.footerText1 = QtWidgets.QLabel(self.centralwidget)
        self.footerText1.setAlignment(QtCore.Qt.AlignVCenter)
        self.footerText1.setObjectName("footerText1")
        self.bottom_footer_2.addWidget(self.footerText1, 0, QtCore.Qt.AlignLeft)
        self.footerText2 = QtWidgets.QLabel(self.centralwidget)
        self.footerText2.setAlignment(QtCore.Qt.AlignCenter)
        self.footerText2.setObjectName("footerText2")
        self.bottom_footer_2.addWidget(self.footerText2, 0, QtCore.Qt.AlignHCenter)
        self.footerText3 = QtWidgets.QLabel(self.centralwidget)
        self.footerText3.setAlignment(QtCore.Qt.AlignVCenter)
        self.footerText3.setObjectName("footerText3")
        self.bottom_footer_2.addWidget(self.footerText3, 0, QtCore.Qt.AlignRight)
        self.footerMainLayout.addLayout(self.bottom_footer_2)
        self.gridLayout_2.addLayout(self.footerMainLayout, 9, 0, 1, 2)
        self.chatBoxWrapper = QtWidgets.QWidget(self.centralwidget)
        self.chatBoxWrapper.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatBoxWrapper.sizePolicy().hasHeightForWidth())
        self.chatBoxWrapper.setSizePolicy(sizePolicy)
        self.chatBoxWrapper.setMinimumSize(QtCore.QSize(0, 150))
        self.chatBoxWrapper.setMaximumSize(QtCore.QSize(16777215, 250))
        self.chatBoxWrapper.setStyleSheet("#chatBoxWrapper {\n"
"    background-color: rgba(15, 23, 42, 0.90); /* deep bluish-black with opacity */\n"
"    border-radius: 12px;\n"
"    border: 1.2px solid rgba(34, 211, 238, 0.45); /* cyan border */\n"
"}\n"
"")
        self.chatBoxWrapper.setObjectName("chatBoxWrapper")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.chatBoxWrapper)
        self.verticalLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chatBoxLogo = QtWidgets.QPushButton(self.chatBoxWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatBoxLogo.sizePolicy().hasHeightForWidth())
        self.chatBoxLogo.setSizePolicy(sizePolicy)
        self.chatBoxLogo.setMinimumSize(QtCore.QSize(32, 32))
        self.chatBoxLogo.setMaximumSize(QtCore.QSize(32, 32))
        self.chatBoxLogo.setStyleSheet("#chatBoxLogo {\n"
"    min-width:32px; max-width:32px; min-height:32px; max-height:32px;\n"
"    border-radius:16px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #22d3ee, stop:1 #3b82f6);\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"")
        self.chatBoxLogo.setIconSize(QtCore.QSize(16, 16))
        self.chatBoxLogo.setObjectName("chatBoxLogo")
        self.horizontalLayout.addWidget(self.chatBoxLogo)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chatHeader = QtWidgets.QLabel(self.chatBoxWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatHeader.sizePolicy().hasHeightForWidth())
        self.chatHeader.setSizePolicy(sizePolicy)
        self.chatHeader.setStyleSheet("#chatHeader { color: #67e8f9; font-family: \"Audiowide\"; font-size: 16px; letter-spacing:1.2px; background:transparent;}\n"
"")
        self.chatHeader.setObjectName("chatHeader")
        self.verticalLayout_2.addWidget(self.chatHeader)
        self.chatSubheading = QtWidgets.QLabel(self.chatBoxWrapper)
        self.chatSubheading.setStyleSheet("#chatSubheading { color: #94a3b8; font-size: 12px; font-style: italic; background:transparent;}\n"
"")
        self.chatSubheading.setObjectName("chatSubheading")
        self.verticalLayout_2.addWidget(self.chatSubheading)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.chatCloseBtn = QtWidgets.QPushButton(self.chatBoxWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatCloseBtn.sizePolicy().hasHeightForWidth())
        self.chatCloseBtn.setSizePolicy(sizePolicy)
        self.chatCloseBtn.setStyleSheet("#chatCloseBtn {\n"
"  min-width:22px; min-height:22px; max-width:22px; max-height:22px;\n"
"  border-radius: 5px;\n"
"  background: rgba(34,211,238,0.15);\n"
"  color: #67e8f9;\n"
"  qproperty-iconSize: 16px 16px;\n"
"  border: 1px solid rgba(34,211,238,0.22);\n"
"}\n"
"#chatCloseBtn:hover { background: rgba(34,211,238,0.23);}\n"
"")
        self.chatCloseBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatCloseBtn.setIcon(icon1)
        self.chatCloseBtn.setObjectName("chatCloseBtn")
        self.horizontalLayout.addWidget(self.chatCloseBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chatArea = QtWidgets.QTextEdit(self.chatBoxWrapper)
        self.chatArea.setMinimumSize(QtCore.QSize(0, 0))
        self.chatArea.setStyleSheet("#chatArea{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"      stop:0 rgba(34,211,238,.22), stop:1 rgba(59,130,246,0.16));\n"
"    color: #67e8f9;\n"
"    border: 1px solid rgba(34,211,238,0.5);\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    box-shadow: 0px 3px 24px 0px rgba(34,211,238,0.15);\n"
"    font-size: 15px;\n"
"    font-family: \'Exo\', \'Segoe UI\', sans-serif;\n"
"\n"
"}")
        self.chatArea.setObjectName("chatArea")
        self.verticalLayout.addWidget(self.chatArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.chatBoxWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit {\n"
"    background: rgba(0,0,0,0.6);\n"
"    border: 1.3px solid rgba(34,211,238,0.55);\n"
"    border-radius: 10px;\n"
"    color: #67e8f9;\n"
"    padding: 6px 14px;\n"
"    font-family: \'Exo\', \'Segoe UI\', sans-serif;\n"
"    font-size: 12px;\n"
"}\n"
"QLineEdit#lineEdit:focus {\n"
"    border: 1.5px solid #22d3ee;\n"
"    outline: none;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.chatBoxWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(46, 38))
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #22d3ee,stop:1 #3b82f6);\n"
"    color: #fff;\n"
"    border: 1px solid rgba(34,211,238,0.5);\n"
"    border-radius: 7px;\n"
"    min-width: 36px; min-height: 36px; max-width:36px; max-height:36px;\n"
"    margin-left: 8px;\n"
"    font-size:18px;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #67e8f9,stop:1 #3b82f6);\n"
"    box-shadow: 0 0 8px 2px rgba(34,211,238,0.32);\n"
"    transform: scale(1.10);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.chatBoxWrapper, 8, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.micBoxWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micBoxWidget.sizePolicy().hasHeightForWidth())
        self.micBoxWidget.setSizePolicy(sizePolicy)
        self.micBoxWidget.setStyleSheet("#micBoxWrapper {\n"
"  border-radius: 10px;\n"
"}\n"
"   ")
        self.micBoxWidget.setObjectName("micBoxWidget")
        self.micBoxLayout = QtWidgets.QVBoxLayout(self.micBoxWidget)
        self.micBoxLayout.setContentsMargins(10, 10, 10, 10)
        self.micBoxLayout.setSpacing(7)
        self.micBoxLayout.setObjectName("micBoxLayout")
        self.MicContainerLayout = QtWidgets.QVBoxLayout()
        self.MicContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.MicContainerLayout.setSpacing(0)
        self.MicContainerLayout.setObjectName("MicContainerLayout")
        self.MicLabelHeading = QtWidgets.QLabel(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicLabelHeading.sizePolicy().hasHeightForWidth())
        self.MicLabelHeading.setSizePolicy(sizePolicy)
        self.MicLabelHeading.setStyleSheet("color: #67e8f9; letter-spacing: 1px;\n"
"background:transparent;")
        self.MicLabelHeading.setObjectName("MicLabelHeading")
        self.MicContainerLayout.addWidget(self.MicLabelHeading, 0, QtCore.Qt.AlignHCenter)
        self.MicLabelSubheading = QtWidgets.QLabel(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicLabelSubheading.sizePolicy().hasHeightForWidth())
        self.MicLabelSubheading.setSizePolicy(sizePolicy)
        self.MicLabelSubheading.setStyleSheet("color: #9ca3af;\n"
"margin-bottom: 8px;\n"
"background:transparent;")
        self.MicLabelSubheading.setObjectName("MicLabelSubheading")
        self.MicContainerLayout.addWidget(self.MicLabelSubheading, 0, QtCore.Qt.AlignHCenter)
        self.MicIcon = QtWidgets.QPushButton(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicIcon.sizePolicy().hasHeightForWidth())
        self.MicIcon.setSizePolicy(sizePolicy)
        self.MicIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.MicIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.MicIcon.setStyleSheet("\n"
"#MicIcon{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #06b6d4,                 stop:1 #2563eb);\n"
"    border: 2px solid #22d3ee;\n"
"    border-radius: 25px;\n"
"    color: white;\n"
"}\n"
"#MicIcon:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0\n"
"        #67e8f9, stop:1 #3b82f6);\n"
"    border: 2px solid #3b82f6;\n"
"}\n"
"\n"
"\n"
"                                            ")
        self.MicIcon.setText("")
        self.MicIcon.setIconSize(QtCore.QSize(28, 28))
        self.MicIcon.setObjectName("MicIcon")
        self.MicContainerLayout.addWidget(self.MicIcon, 0, QtCore.Qt.AlignHCenter)
        self.micBoxLayout.addLayout(self.MicContainerLayout)
        self.MicStandBy = QtWidgets.QWidget(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicStandBy.sizePolicy().hasHeightForWidth())
        self.MicStandBy.setSizePolicy(sizePolicy)
        self.MicStandBy.setStyleSheet("#MicStandBy{\n"
"    background:transparent;\n"
"    border: 1px solid #6b7280;\n"
"    background-color: rgba(107, 114, 128, 0.2);\n"
"    border-radius: 16px;\n"
"    padding: 4px 12px;\n"
"}")
        self.MicStandBy.setObjectName("MicStandBy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.MicStandBy)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.belowMicDot = QtWidgets.QLabel(self.MicStandBy)
        self.belowMicDot.setMinimumSize(QtCore.QSize(8, 8))
        self.belowMicDot.setMaximumSize(QtCore.QSize(8, 8))
        self.belowMicDot.setStyleSheet("background-color: #9ca3af;\n"
"border-radius: 4px;\n"
"                                                        ")
        self.belowMicDot.setText("")
        self.belowMicDot.setObjectName("belowMicDot")
        self.horizontalLayout_3.addWidget(self.belowMicDot)
        self.belowMicText = QtWidgets.QLabel(self.MicStandBy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belowMicText.sizePolicy().hasHeightForWidth())
        self.belowMicText.setSizePolicy(sizePolicy)
        self.belowMicText.setStyleSheet("#belowMicText{\n"
"    background:transparent;\n"
"    color: #9ca3af;\n"
"}")
        self.belowMicText.setObjectName("belowMicText")
        self.horizontalLayout_3.addWidget(self.belowMicText)
        self.micBoxLayout.addWidget(self.MicStandBy, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.micBoxWidget, 8, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.HeadingLayout = QtWidgets.QVBoxLayout()
        self.HeadingLayout.setContentsMargins(-1, 10, -1, -1)
        self.HeadingLayout.setSpacing(0)
        self.HeadingLayout.setObjectName("HeadingLayout")
        self.titleLabelHeading = QtWidgets.QLabel(self.centralwidget)
        self.titleLabelHeading.setStyleSheet("font-size: 28px;\n"
"        font-weight: bold;\n"
"        font-family: \"Audiowide\";\n"
"        color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #22d3ee, stop:1 #67e8f9);")
        self.titleLabelHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabelHeading.setObjectName("titleLabelHeading")
        self.HeadingLayout.addWidget(self.titleLabelHeading)
        self.subtitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtitleLabel.setStyleSheet("font-size: 14px; font-style: italic;\n"
"        color: rgba(103, 232, 249, 1);")
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.HeadingLayout.addWidget(self.subtitleLabel)
        self.TitleSubheading = QtWidgets.QHBoxLayout()
        self.TitleSubheading.setSpacing(0)
        self.TitleSubheading.setObjectName("TitleSubheading")
        self.Title_subheading_text = QtWidgets.QLabel(self.centralwidget)
        self.Title_subheading_text.setStyleSheet("color: rgba(156, 163, 175, 1)")
        self.Title_subheading_text.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_subheading_text.setObjectName("Title_subheading_text")
        self.TitleSubheading.addWidget(self.Title_subheading_text)
        self.HeadingLayout.addLayout(self.TitleSubheading)
        self.JARVISStatusTexts = QtWidgets.QHBoxLayout()
        self.JARVISStatusTexts.setSpacing(0)
        self.JARVISStatusTexts.setObjectName("JARVISStatusTexts")
        self.statusLabelSubheading = QtWidgets.QLabel(self.centralwidget)
        self.statusLabelSubheading.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"      stop:0 #22d3ee, stop:1 #67e8f9);")
        self.statusLabelSubheading.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabelSubheading.setObjectName("statusLabelSubheading")
        self.JARVISStatusTexts.addWidget(self.statusLabelSubheading)
        self.HeadingLayout.addLayout(self.JARVISStatusTexts)
        self.gridLayout_2.addLayout(self.HeadingLayout, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J.A.R.V.I.S"))
        self.Operation_1.setText(_translate("MainWindow", "Neural Network"))
        self.Title_1.setText(_translate("MainWindow", "ACTIVE"))
        self.Operation_2.setText(_translate("MainWindow", "Voice Recognition"))
        self.Title_2.setText(_translate("MainWindow", "ONLINE"))
        self.Operation_3.setText(_translate("MainWindow", "System Status"))
        self.Title_3.setText(_translate("MainWindow", "OPERATIONAL"))
        self.Operation_4.setText(_translate("MainWindow", "Security Clearance"))
        self.Title_4.setText(_translate("MainWindow", "MAXIMUM"))
        self.Operation_5.setText(_translate("MainWindow", "Network"))
        self.Title_5.setText(_translate("MainWindow", "CONNECTED"))
        self.Operation_6.setText(_translate("MainWindow", "Power Core"))
        self.Title_6.setText(_translate("MainWindow", "OPTIMAL"))
        self.footerText1.setStyleSheet(_translate("MainWindow", "color: #6b7280; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.footerText1.setText(_translate("MainWindow", "STARK INDUSTRIES • MARK 52 INTERFACE"))
        self.footerText2.setStyleSheet(_translate("MainWindow", "color: #6b7280; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.footerText2.setText(_translate("MainWindow", "UPTIME: 847:46:40"))
        self.footerText3.setStyleSheet(_translate("MainWindow", "color: #4ade80; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.footerText3.setText(_translate("MainWindow", "THREAT LEVEL: MINIMAL"))
        self.chatHeader.setText(_translate("MainWindow", "COMMUNICATION"))
        self.chatSubheading.setText(_translate("MainWindow", "Direct Interface"))
        self.pushButton.setText(_translate("MainWindow", "➤"))
        self.MicLabelHeading.setText(_translate("MainWindow", "VOICE COMMAND"))
        self.MicLabelSubheading.setText(_translate("MainWindow", "Click to activate"))
        self.belowMicText.setText(_translate("MainWindow", "STANDBY"))
        self.titleLabelHeading.setText(_translate("MainWindow", "J.A.R.V.I.S"))
        self.subtitleLabel.setText(_translate("MainWindow", "Just A Rather Very Intelligent System"))
        self.Title_subheading_text.setText(_translate("MainWindow", "STARK INDUSTRIES - MARK 52 INTERFACE"))
        self.statusLabelSubheading.setText(_translate("MainWindow", "● ONLINE ● SECURE ● READY"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
