# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# DESKTOP_APP/GUI/new_ui.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(960, 487)
        mainWindow.setStyleSheet("background-color: #0a0f1b;")
        self.mainCentralWidget = QtWidgets.QWidget(mainWindow)
        self.mainCentralWidget.setObjectName("mainCentralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainCentralWidget)
        self.gridLayout_2.setContentsMargins(20, -1, 20, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layoutArcReactorArea = QtWidgets.QGridLayout()
        self.layoutArcReactorArea.setObjectName("layoutArcReactorArea")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutArcReactorArea.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutArcReactorArea.addItem(spacerItem1, 2, 1, 1, 1)
        self.lblArcReactor = QtWidgets.QLabel(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblArcReactor.sizePolicy().hasHeightForWidth())
        self.lblArcReactor.setSizePolicy(sizePolicy)
        self.lblArcReactor.setMinimumSize(QtCore.QSize(200, 200))
        self.lblArcReactor.setMaximumSize(QtCore.QSize(200, 200))
        self.lblArcReactor.setPixmap(QtGui.QPixmap(""))
        self.lblArcReactor.setScaledContents(True)
        self.lblArcReactor.setObjectName("lblArcReactor")
        self.layoutArcReactorArea.addWidget(self.lblArcReactor, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutArcReactorArea.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutArcReactorArea.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.layoutArcReactorArea, 0, 0, 9, 2)
        self.layoutFooterMain = QtWidgets.QVBoxLayout()
        self.layoutFooterMain.setObjectName("layoutFooterMain")
        self.lineFooterTop = QtWidgets.QFrame(self.mainCentralWidget)
        self.lineFooterTop.setStyleSheet("background-color: rgba(34, 211, 238, 0.3);")
        self.lineFooterTop.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineFooterTop.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineFooterTop.setObjectName("lineFooterTop")
        self.layoutFooterMain.addWidget(self.lineFooterTop)
        self.layoutStatusRow = QtWidgets.QHBoxLayout()
        self.layoutStatusRow.setContentsMargins(10, -1, 10, -1)
        self.layoutStatusRow.setSpacing(0)
        self.layoutStatusRow.setObjectName("layoutStatusRow")
        self.layoutStatusNN = QtWidgets.QHBoxLayout()
        self.layoutStatusNN.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN.setSpacing(6)
        self.layoutStatusNN.setObjectName("layoutStatusNN")
        self.layoutStatusNNLabels = QtWidgets.QVBoxLayout()
        self.layoutStatusNNLabels.setObjectName("layoutStatusNNLabels")
        self.lblStatusNNTitle = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNTitle.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.lblStatusNNTitle.setObjectName("lblStatusNNTitle")
        self.layoutStatusNNLabels.addWidget(self.lblStatusNNTitle)
        self.lblStatusNNValue = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue.setStyleSheet("color: gray;")
        self.lblStatusNNValue.setObjectName("lblStatusNNValue")
        self.layoutStatusNNLabels.addWidget(self.lblStatusNNValue)
        self.layoutStatusNN.addLayout(self.layoutStatusNNLabels)
        self.btnStatusNNDot = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot.setSizePolicy(sizePolicy)
        self.btnStatusNNDot.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #4ade80;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStatusNNDot.setIcon(icon)
        self.btnStatusNNDot.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot.setObjectName("btnStatusNNDot")
        self.layoutStatusNN.addWidget(self.btnStatusNNDot, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN)
        self.layoutStatusNN_2 = QtWidgets.QHBoxLayout()
        self.layoutStatusNN_2.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN_2.setSpacing(6)
        self.layoutStatusNN_2.setObjectName("layoutStatusNN_2")
        self.layoutStatusNNLabels_2 = QtWidgets.QVBoxLayout()
        self.layoutStatusNNLabels_2.setObjectName("layoutStatusNNLabels_2")
        self.lblStatusNNTitle_2 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNTitle_2.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.lblStatusNNTitle_2.setObjectName("lblStatusNNTitle_2")
        self.layoutStatusNNLabels_2.addWidget(self.lblStatusNNTitle_2)
        self.lblStatusNNValue_2 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue_2.setStyleSheet("color: gray;")
        self.lblStatusNNValue_2.setObjectName("lblStatusNNValue_2")
        self.layoutStatusNNLabels_2.addWidget(self.lblStatusNNValue_2)
        self.layoutStatusNN_2.addLayout(self.layoutStatusNNLabels_2)
        self.btnStatusNNDot_2 = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot_2.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot_2.setSizePolicy(sizePolicy)
        self.btnStatusNNDot_2.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_2.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_2.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #22d3ee;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        self.btnStatusNNDot_2.setIcon(icon)
        self.btnStatusNNDot_2.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot_2.setObjectName("btnStatusNNDot_2")
        self.layoutStatusNN_2.addWidget(self.btnStatusNNDot_2, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN_2)
        self.layoutStatusNN_3 = QtWidgets.QHBoxLayout()
        self.layoutStatusNN_3.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN_3.setSpacing(6)
        self.layoutStatusNN_3.setObjectName("layoutStatusNN_3")
        self.layoutStatusNNLabels_3 = QtWidgets.QVBoxLayout()
        self.layoutStatusNNLabels_3.setObjectName("layoutStatusNNLabels_3")
        self.Operation_3 = QtWidgets.QLabel(self.mainCentralWidget)
        self.Operation_3.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.Operation_3.setObjectName("Operation_3")
        self.layoutStatusNNLabels_3.addWidget(self.Operation_3)
        self.lblStatusNNValue_3 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue_3.setStyleSheet("color: gray;")
        self.lblStatusNNValue_3.setObjectName("lblStatusNNValue_3")
        self.layoutStatusNNLabels_3.addWidget(self.lblStatusNNValue_3)
        self.layoutStatusNN_3.addLayout(self.layoutStatusNNLabels_3)
        self.btnStatusNNDot_3 = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot_3.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot_3.setSizePolicy(sizePolicy)
        self.btnStatusNNDot_3.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_3.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_3.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #60a5fa;\n"
"    }\n"
"   ")
        self.btnStatusNNDot_3.setIcon(icon)
        self.btnStatusNNDot_3.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot_3.setObjectName("btnStatusNNDot_3")
        self.layoutStatusNN_3.addWidget(self.btnStatusNNDot_3, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN_3)
        self.layoutStatusNN_4 = QtWidgets.QHBoxLayout()
        self.layoutStatusNN_4.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN_4.setSpacing(6)
        self.layoutStatusNN_4.setObjectName("layoutStatusNN_4")
        self.StatusLabelLayout4 = QtWidgets.QVBoxLayout()
        self.StatusLabelLayout4.setObjectName("StatusLabelLayout4")
        self.lblStatusNNTitle_3 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNTitle_3.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.lblStatusNNTitle_3.setObjectName("lblStatusNNTitle_3")
        self.StatusLabelLayout4.addWidget(self.lblStatusNNTitle_3)
        self.lblStatusNNValue_4 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue_4.setStyleSheet("color: gray;")
        self.lblStatusNNValue_4.setObjectName("lblStatusNNValue_4")
        self.StatusLabelLayout4.addWidget(self.lblStatusNNValue_4)
        self.layoutStatusNN_4.addLayout(self.StatusLabelLayout4)
        self.btnStatusNNDot_4 = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot_4.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot_4.setSizePolicy(sizePolicy)
        self.btnStatusNNDot_4.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_4.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_4.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #818cf8;\n"
"    }\n"
"   ")
        self.btnStatusNNDot_4.setIcon(icon)
        self.btnStatusNNDot_4.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot_4.setObjectName("btnStatusNNDot_4")
        self.layoutStatusNN_4.addWidget(self.btnStatusNNDot_4, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN_4)
        self.layoutStatusNN_5 = QtWidgets.QHBoxLayout()
        self.layoutStatusNN_5.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN_5.setSpacing(6)
        self.layoutStatusNN_5.setObjectName("layoutStatusNN_5")
        self.layoutStatusNNLabels_4 = QtWidgets.QVBoxLayout()
        self.layoutStatusNNLabels_4.setObjectName("layoutStatusNNLabels_4")
        self.lblStatusNNTitle_4 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNTitle_4.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.lblStatusNNTitle_4.setObjectName("lblStatusNNTitle_4")
        self.layoutStatusNNLabels_4.addWidget(self.lblStatusNNTitle_4)
        self.lblStatusNNValue_5 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue_5.setStyleSheet("color: gray;")
        self.lblStatusNNValue_5.setObjectName("lblStatusNNValue_5")
        self.layoutStatusNNLabels_4.addWidget(self.lblStatusNNValue_5)
        self.layoutStatusNN_5.addLayout(self.layoutStatusNNLabels_4)
        self.btnStatusNNDot_5 = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot_5.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot_5.setSizePolicy(sizePolicy)
        self.btnStatusNNDot_5.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_5.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_5.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #10b981;\n"
"      qproperty-icon: url(:/icons/.guivenv/mic_icon.svg);\n"
"      qproperty-iconSize: 30px 30px;\n"
"    }\n"
"   ")
        self.btnStatusNNDot_5.setIcon(icon)
        self.btnStatusNNDot_5.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot_5.setObjectName("btnStatusNNDot_5")
        self.layoutStatusNN_5.addWidget(self.btnStatusNNDot_5, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN_5)
        self.layoutStatusNN_6 = QtWidgets.QHBoxLayout()
        self.layoutStatusNN_6.setContentsMargins(-1, -1, 15, -1)
        self.layoutStatusNN_6.setSpacing(6)
        self.layoutStatusNN_6.setObjectName("layoutStatusNN_6")
        self.layoutStatusNNLabels_5 = QtWidgets.QVBoxLayout()
        self.layoutStatusNNLabels_5.setObjectName("layoutStatusNNLabels_5")
        self.lblStatusNNTitle_5 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNTitle_5.setStyleSheet("color: #4ade80; font-weight: bold;")
        self.lblStatusNNTitle_5.setObjectName("lblStatusNNTitle_5")
        self.layoutStatusNNLabels_5.addWidget(self.lblStatusNNTitle_5)
        self.lblStatusNNValue_6 = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblStatusNNValue_6.setStyleSheet("color: gray;")
        self.lblStatusNNValue_6.setObjectName("lblStatusNNValue_6")
        self.layoutStatusNNLabels_5.addWidget(self.lblStatusNNValue_6)
        self.layoutStatusNN_6.addLayout(self.layoutStatusNNLabels_5)
        self.btnStatusNNDot_6 = QtWidgets.QPushButton(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatusNNDot_6.sizePolicy().hasHeightForWidth())
        self.btnStatusNNDot_6.setSizePolicy(sizePolicy)
        self.btnStatusNNDot_6.setMinimumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_6.setMaximumSize(QtCore.QSize(8, 8))
        self.btnStatusNNDot_6.setStyleSheet("\n"
"    QPushButton {\n"
"      border-radius: 4px;\n"
"      background-color: #facc15;\n"
"    }\n"
"   ")
        self.btnStatusNNDot_6.setIcon(icon)
        self.btnStatusNNDot_6.setIconSize(QtCore.QSize(30, 30))
        self.btnStatusNNDot_6.setObjectName("btnStatusNNDot_6")
        self.layoutStatusNN_6.addWidget(self.btnStatusNNDot_6, 0, QtCore.Qt.AlignLeft)
        self.layoutStatusRow.addLayout(self.layoutStatusNN_6)
        self.layoutFooterMain.addLayout(self.layoutStatusRow)
        self.lineFooterBottom = QtWidgets.QFrame(self.mainCentralWidget)
        self.lineFooterBottom.setStyleSheet("background-color: rgba(34, 211, 238, 0.3);")
        self.lineFooterBottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineFooterBottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineFooterBottom.setObjectName("lineFooterBottom")
        self.layoutFooterMain.addWidget(self.lineFooterBottom)
        self.layoutFooterInfo = QtWidgets.QHBoxLayout()
        self.layoutFooterInfo.setContentsMargins(10, -1, 10, 0)
        self.layoutFooterInfo.setObjectName("layoutFooterInfo")
        self.lblFooterSignature = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblFooterSignature.setAlignment(QtCore.Qt.AlignVCenter)
        self.lblFooterSignature.setObjectName("lblFooterSignature")
        self.layoutFooterInfo.addWidget(self.lblFooterSignature, 0, QtCore.Qt.AlignLeft)
        self.lblFooterUptime = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblFooterUptime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFooterUptime.setObjectName("lblFooterUptime")
        self.layoutFooterInfo.addWidget(self.lblFooterUptime, 0, QtCore.Qt.AlignHCenter)
        self.lblFooterThreat = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblFooterThreat.setAlignment(QtCore.Qt.AlignVCenter)
        self.lblFooterThreat.setObjectName("lblFooterThreat")
        self.layoutFooterInfo.addWidget(self.lblFooterThreat, 0, QtCore.Qt.AlignRight)
        self.layoutFooterMain.addLayout(self.layoutFooterInfo)
        self.gridLayout_2.addLayout(self.layoutFooterMain, 9, 0, 1, 2)
        self.widgetChatBox = QtWidgets.QWidget(self.mainCentralWidget)
        self.widgetChatBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetChatBox.sizePolicy().hasHeightForWidth())
        self.widgetChatBox.setSizePolicy(sizePolicy)
        self.widgetChatBox.setMinimumSize(QtCore.QSize(0, 150))
        self.widgetChatBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widgetChatBox.setStyleSheet("#chatBoxWrapper {\n"
"    background-color: rgba(15, 23, 42, 0.90); /* deep bluish-black with opacity */\n"
"    border-radius: 12px;\n"
"    border: 1.2px solid rgba(34, 211, 238, 0.45); /* cyan border */\n"
"}\n"
"")
        self.widgetChatBox.setObjectName("widgetChatBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetChatBox)
        self.verticalLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutChatVertical = QtWidgets.QVBoxLayout()
        self.layoutChatVertical.setObjectName("layoutChatVertical")
        self.layoutChatHeader = QtWidgets.QHBoxLayout()
        self.layoutChatHeader.setSpacing(6)
        self.layoutChatHeader.setObjectName("layoutChatHeader")
        self.btnChatHeaderLogo = QtWidgets.QPushButton(self.widgetChatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChatHeaderLogo.sizePolicy().hasHeightForWidth())
        self.btnChatHeaderLogo.setSizePolicy(sizePolicy)
        self.btnChatHeaderLogo.setMinimumSize(QtCore.QSize(32, 32))
        self.btnChatHeaderLogo.setMaximumSize(QtCore.QSize(32, 32))
        self.btnChatHeaderLogo.setStyleSheet("#btnChatHeaderLogo {\n"
"    min-width:32px; max-width:32px; min-height:32px; max-height:32px;\n"
"    border-radius:16px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #22d3ee, stop:1 #3b82f6);\n"
"    display: flex;\n"
"    align-items: center;\n"
"    justify-content: center;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChatHeaderLogo.setIcon(icon1)
        self.btnChatHeaderLogo.setIconSize(QtCore.QSize(16, 16))
        self.btnChatHeaderLogo.setObjectName("btnChatHeaderLogo")
        self.layoutChatHeader.addWidget(self.btnChatHeaderLogo)
        self.layoutChatHeaderInfo_2 = QtWidgets.QVBoxLayout()
        self.layoutChatHeaderInfo_2.setSpacing(0)
        self.layoutChatHeaderInfo_2.setObjectName("layoutChatHeaderInfo_2")
        self.lblChatHeaderTitle = QtWidgets.QLabel(self.widgetChatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblChatHeaderTitle.sizePolicy().hasHeightForWidth())
        self.lblChatHeaderTitle.setSizePolicy(sizePolicy)
        self.lblChatHeaderTitle.setAutoFillBackground(False)
        self.lblChatHeaderTitle.setStyleSheet("#lblChatHeaderTitle { color: #67e8f9; font-family: \"Audiowide\"; font-size: 16px; letter-spacing:1.2px; background:transparent;}\n"
"")
        self.lblChatHeaderTitle.setObjectName("lblChatHeaderTitle")
        self.layoutChatHeaderInfo_2.addWidget(self.lblChatHeaderTitle)
        self.lblChatHeaderSubtitle = QtWidgets.QLabel(self.widgetChatBox)
        self.lblChatHeaderSubtitle.setStyleSheet("#lblChatHeaderSubtitle { color: #94a3b8; font-size: 12px; font-style: italic; background:transparent;}\n"
"")
        self.lblChatHeaderSubtitle.setObjectName("lblChatHeaderSubtitle")
        self.layoutChatHeaderInfo_2.addWidget(self.lblChatHeaderSubtitle)
        self.layoutChatHeader.addLayout(self.layoutChatHeaderInfo_2)
        self.btnCloseChat = QtWidgets.QPushButton(self.widgetChatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloseChat.sizePolicy().hasHeightForWidth())
        self.btnCloseChat.setSizePolicy(sizePolicy)
        self.btnCloseChat.setStyleSheet("#chatCloseBtn {\n"
"  min-width:22px; min-height:22px; max-width:22px; max-height:22px;\n"
"  border-radius: 5px;\n"
"  background: rgba(34,211,238,0.15);\n"
"  color: #67e8f9;\n"
"  qproperty-iconSize: 16px 16px;\n"
"  border: 1px solid rgba(34,211,238,0.22);\n"
"}\n"
"#chatCloseBtn:hover { background: rgba(34,211,238,0.23);}\n"
"")
        self.btnCloseChat.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCloseChat.setIcon(icon2)
        self.btnCloseChat.setIconSize(QtCore.QSize(16, 16))
        self.btnCloseChat.setObjectName("btnCloseChat")
        self.layoutChatHeader.addWidget(self.btnCloseChat)
        self.layoutChatVertical.addLayout(self.layoutChatHeader)
        self.txtChatHistory = QtWidgets.QTextEdit(self.widgetChatBox)
        self.txtChatHistory.setMinimumSize(QtCore.QSize(0, 0))
        self.txtChatHistory.setStyleSheet("#txtChatHistory{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"      stop:0 rgba(34,211,238,.22), stop:1 rgba(59,130,246,0.16));\n"
"    color: #67e8f9;\n"
"    border: 1px solid rgba(34,211,238,0.5);\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    box-shadow: 0px 3px 24px 0px rgba(34,211,238,0.15);\n"
"    font-size: 10px;\n"
"    font-family: \'Exo\', \'Segoe UI\', sans-serif;\n"
"\n"
"}")
        self.txtChatHistory.setObjectName("txtChatHistory")
        self.layoutChatVertical.addWidget(self.txtChatHistory)
        self.layoutChatInput = QtWidgets.QHBoxLayout()
        self.layoutChatInput.setObjectName("layoutChatInput")
        self.txtChatInput = QtWidgets.QLineEdit(self.widgetChatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtChatInput.sizePolicy().hasHeightForWidth())
        self.txtChatInput.setSizePolicy(sizePolicy)
        self.txtChatInput.setStyleSheet("QLineEdit#txtChatInput {\n"
"    background: rgba(0,0,0,0.6);\n"
"    border: 1.3px solid rgba(34,211,238,0.55);\n"
"    border-radius: 10px;\n"
"    color: #67e8f9;\n"
"    padding: 6px 14px;\n"
"    font-family: \'Exo\', \'Segoe UI\', sans-serif;\n"
"    font-size: 12px;\n"
"}\n"
"QLineEdit#txtChatInput:focus {\n"
"    border: 1.5px solid #22d3ee;\n"
"    outline: none;\n"
"}\n"
"")
        self.txtChatInput.setObjectName("txtChatInput")
        self.layoutChatInput.addWidget(self.txtChatInput)
        self.btnChatSend = QtWidgets.QPushButton(self.widgetChatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChatSend.sizePolicy().hasHeightForWidth())
        self.btnChatSend.setSizePolicy(sizePolicy)
        self.btnChatSend.setMaximumSize(QtCore.QSize(46, 38))
        self.btnChatSend.setStyleSheet("QPushButton#btnChatSend {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #22d3ee,stop:1 #3b82f6);\n"
"    color: #fff;\n"
"    border: 1px solid rgba(34,211,238,0.5);\n"
"    border-radius: 7px;\n"
"    min-width: 36px; min-height: 36px; max-width:36px; max-height:36px;\n"
"    margin-left: 8px;\n"
"    font-size:18px;\n"
"}\n"
"QPushButton#btnChatSend:hover {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #67e8f9,stop:1 #3b82f6);\n"
"    box-shadow: 0 0 8px 2px rgba(34,211,238,0.32);\n"
"    transform: scale(1.10);\n"
"}\n"
"")
        self.btnChatSend.setObjectName("btnChatSend")
        self.layoutChatInput.addWidget(self.btnChatSend)
        self.layoutChatVertical.addLayout(self.layoutChatInput)
        self.verticalLayout_4.addLayout(self.layoutChatVertical)
        self.gridLayout_2.addWidget(self.widgetChatBox, 8, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.micBoxWidget = QtWidgets.QWidget(self.mainCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micBoxWidget.sizePolicy().hasHeightForWidth())
        self.micBoxWidget.setSizePolicy(sizePolicy)
        self.micBoxWidget.setStyleSheet("#micBoxWrapper {\n"
"  border-radius: 10px;\n"
"}\n"
"   ")
        self.micBoxWidget.setObjectName("micBoxWidget")
        self.micBoxLayout = QtWidgets.QVBoxLayout(self.micBoxWidget)
        self.micBoxLayout.setContentsMargins(10, 10, 10, 10)
        self.micBoxLayout.setSpacing(7)
        self.micBoxLayout.setObjectName("micBoxLayout")
        self.MicContainerLayout = QtWidgets.QVBoxLayout()
        self.MicContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.MicContainerLayout.setSpacing(0)
        self.MicContainerLayout.setObjectName("MicContainerLayout")
        self.MicLabelHeading = QtWidgets.QLabel(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicLabelHeading.sizePolicy().hasHeightForWidth())
        self.MicLabelHeading.setSizePolicy(sizePolicy)
        self.MicLabelHeading.setStyleSheet("color: #67e8f9; letter-spacing: 1px;\n"
"background:transparent;")
        self.MicLabelHeading.setObjectName("MicLabelHeading")
        self.MicContainerLayout.addWidget(self.MicLabelHeading, 0, QtCore.Qt.AlignHCenter)
        self.MicLabelSubheading = QtWidgets.QLabel(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicLabelSubheading.sizePolicy().hasHeightForWidth())
        self.MicLabelSubheading.setSizePolicy(sizePolicy)
        self.MicLabelSubheading.setStyleSheet("color: #9ca3af;\n"
"margin-bottom: 8px;\n"
"background:transparent;")
        self.MicLabelSubheading.setObjectName("MicLabelSubheading")
        self.MicContainerLayout.addWidget(self.MicLabelSubheading, 0, QtCore.Qt.AlignHCenter)
        self.MicIcon = QtWidgets.QPushButton(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicIcon.sizePolicy().hasHeightForWidth())
        self.MicIcon.setSizePolicy(sizePolicy)
        self.MicIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.MicIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.MicIcon.setStyleSheet("\n"
"#MicIcon{\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #06b6d4,                 stop:1 #2563eb);\n"
"    border: 2px solid #22d3ee;\n"
"    border-radius: 25px;\n"
"    color: white;\n"
"}\n"
"#MicIcon:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0\n"
"        #67e8f9, stop:1 #3b82f6);\n"
"    border: 2px solid #3b82f6;\n"
"}\n"
"\n"
"\n"
"                                            ")
        self.MicIcon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MicIcon.setIcon(icon3)
        self.MicIcon.setIconSize(QtCore.QSize(28, 28))
        self.MicIcon.setObjectName("MicIcon")
        self.MicContainerLayout.addWidget(self.MicIcon, 0, QtCore.Qt.AlignHCenter)
        self.micBoxLayout.addLayout(self.MicContainerLayout)
        self.MicStandBy = QtWidgets.QWidget(self.micBoxWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MicStandBy.sizePolicy().hasHeightForWidth())
        self.MicStandBy.setSizePolicy(sizePolicy)
        self.MicStandBy.setStyleSheet("#MicStandBy{\n"
"    background:transparent;\n"
"    border: 1px solid #6b7280;\n"
"    background-color: rgba(107, 114, 128, 0.2);\n"
"    border-radius: 16px;\n"
"    padding: 4px 12px;\n"
"}")
        self.MicStandBy.setObjectName("MicStandBy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.MicStandBy)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.belowMicDot = QtWidgets.QLabel(self.MicStandBy)
        self.belowMicDot.setMinimumSize(QtCore.QSize(8, 8))
        self.belowMicDot.setMaximumSize(QtCore.QSize(8, 8))
        self.belowMicDot.setStyleSheet("background-color: #9ca3af;\n"
"border-radius: 4px;\n"
"                                                        ")
        self.belowMicDot.setText("")
        self.belowMicDot.setObjectName("belowMicDot")
        self.horizontalLayout_3.addWidget(self.belowMicDot)
        self.belowMicText = QtWidgets.QLabel(self.MicStandBy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belowMicText.sizePolicy().hasHeightForWidth())
        self.belowMicText.setSizePolicy(sizePolicy)
        self.belowMicText.setStyleSheet("#belowMicText{\n"
"    background:transparent;\n"
"    color: #9ca3af;\n"
"}")
        self.belowMicText.setObjectName("belowMicText")
        self.horizontalLayout_3.addWidget(self.belowMicText)
        self.micBoxLayout.addWidget(self.MicStandBy, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.micBoxWidget, 8, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.layoutHeaderMain = QtWidgets.QVBoxLayout()
        self.layoutHeaderMain.setContentsMargins(-1, 10, -1, -1)
        self.layoutHeaderMain.setSpacing(0)
        self.layoutHeaderMain.setObjectName("layoutHeaderMain")
        self.lblHeaderTitle = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblHeaderTitle.setStyleSheet("font-size: 28px;\n"
"        font-weight: bold;\n"
"        font-family: \"Audiowide\";\n"
"        color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #22d3ee, stop:1 #67e8f9);")
        self.lblHeaderTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderTitle.setObjectName("lblHeaderTitle")
        self.layoutHeaderMain.addWidget(self.lblHeaderTitle)
        self.lblHeaderSubtitle = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblHeaderSubtitle.setStyleSheet("font-size: 14px; font-style: italic;\n"
"        color: rgba(103, 232, 249, 1);")
        self.lblHeaderSubtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderSubtitle.setObjectName("lblHeaderSubtitle")
        self.layoutHeaderMain.addWidget(self.lblHeaderSubtitle)
        self.layoutHeaderSubheading = QtWidgets.QHBoxLayout()
        self.layoutHeaderSubheading.setSpacing(0)
        self.layoutHeaderSubheading.setObjectName("layoutHeaderSubheading")
        self.lblHeaderMarkID = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblHeaderMarkID.setStyleSheet("color: rgba(156, 163, 175, 1)")
        self.lblHeaderMarkID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderMarkID.setObjectName("lblHeaderMarkID")
        self.layoutHeaderSubheading.addWidget(self.lblHeaderMarkID)
        self.layoutHeaderMain.addLayout(self.layoutHeaderSubheading)
        self.layoutHeaderStatus = QtWidgets.QHBoxLayout()
        self.layoutHeaderStatus.setSpacing(0)
        self.layoutHeaderStatus.setObjectName("layoutHeaderStatus")
        self.lblHeaderSystemStatus = QtWidgets.QLabel(self.mainCentralWidget)
        self.lblHeaderSystemStatus.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"      stop:0 #22d3ee, stop:1 #67e8f9);")
        self.lblHeaderSystemStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderSystemStatus.setObjectName("lblHeaderSystemStatus")
        self.layoutHeaderStatus.addWidget(self.lblHeaderSystemStatus)
        self.layoutHeaderMain.addLayout(self.layoutHeaderStatus)
        self.gridLayout_2.addLayout(self.layoutHeaderMain, 0, 0, 1, 2)
        mainWindow.setCentralWidget(self.mainCentralWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "J.A.R.V.I.S"))
        self.lblStatusNNTitle.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue.setText(_translate("mainWindow", "Neural Network"))
        self.lblStatusNNTitle_2.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue_2.setText(_translate("mainWindow", "Neural Network"))
        self.Operation_3.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue_3.setText(_translate("mainWindow", "Neural Network"))
        self.lblStatusNNTitle_3.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue_4.setText(_translate("mainWindow", "Neural Network"))
        self.lblStatusNNTitle_4.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue_5.setText(_translate("mainWindow", "Neural Network"))
        self.lblStatusNNTitle_5.setText(_translate("mainWindow", "ACTIVE"))
        self.lblStatusNNValue_6.setText(_translate("mainWindow", "Neural Network"))
        self.lblFooterSignature.setStyleSheet(_translate("mainWindow", "color: #6b7280; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.lblFooterSignature.setText(_translate("mainWindow", "STARK INDUSTRIES • MARK 52 INTERFACE"))
        self.lblFooterUptime.setStyleSheet(_translate("mainWindow", "color: #6b7280; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.lblFooterUptime.setText(_translate("mainWindow", "UPTIME: 847:46:40"))
        self.lblFooterThreat.setStyleSheet(_translate("mainWindow", "color: #4ade80; font-family: \'Audiowide\'; letter-spacing: 0.5px;\n"
"                                            "))
        self.lblFooterThreat.setText(_translate("mainWindow", "THREAT LEVEL: MINIMAL"))
        self.lblChatHeaderTitle.setText(_translate("mainWindow", "COMMUNICATION"))
        self.lblChatHeaderSubtitle.setText(_translate("mainWindow", "Direct Interface"))
        self.txtChatHistory.setPlaceholderText(_translate("mainWindow", "Hi , I am your personal assistant ."))
        self.btnChatSend.setText(_translate("mainWindow", "➤"))
        self.MicLabelHeading.setText(_translate("mainWindow", "VOICE COMMAND"))
        self.MicLabelSubheading.setText(_translate("mainWindow", "Click to activate"))
        self.belowMicText.setText(_translate("mainWindow", "STANDBY"))
        self.lblHeaderTitle.setText(_translate("mainWindow", "J.A.R.V.I.S"))
        self.lblHeaderSubtitle.setText(_translate("mainWindow", "Just A Rather Very Intelligent System"))
        self.lblHeaderMarkID.setText(_translate("mainWindow", "STARK INDUSTRIES - MARK 52 INTERFACE"))
        self.lblHeaderSystemStatus.setText(_translate("mainWindow", "● ONLINE ● SECURE ● READY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
