# app_map.py
# This file maps the 'app_name' entity to a real command or URL.

# 1. Mappings for local applications
# These are commands that run in the Windows 'start' command.
LOCAL_APPS = {
    "chrome": "start chrome",
    "google chrome": "start chrome",
    "visual studio code": "start code",
    "vs code": "start code",
    "edge": "start msedge",
    "notepad": "start notepad",
    "notepad++": "start notepad++",
    "calculator": "start calc",
    "spotify": "start spotify",
    "vlc": "start vlc",
    "terminal": "start cmd",
    "cmd": "start cmd",
    "word": "start winword",
    "excel": "start excel",
    "powerpoint": "start powerpnt",
    "task manager": "start taskmgr",
    "control panel": "start control",
    "file explorer": "start explorer",
    "explorer": "start explorer",
    "settings": "start ms-settings:",
    "system settings": "start ms-settings:",
    "camera": "start microsoft.windows.camera:",
    "photos": "start ms-photos:",
    "maps": "start bingmaps:",
    "google maps": "start bingmaps:",
    "slack": "start slack",
    "zoom": "start zoom",
    "photoshop": "start photoshop",
    "filezilla": "start filezilla",
    "obs studio": "start obs64", # (check your shortcut name)
    "blender": "start blender",
    "brave": "start brave",
    "opera": "start opera",
    "discord": "start discord",
    "telegram": "start telegram",
    "whatsapp desktop": "start whatsapp",
    "whatsapp": "start whatsapp",
    "steam": "start steam",
    "sublime text": "start sublime_text",
    "sublime": "start sublime_text",
    "postman": "start postman",
    "docker desktop": "start Docker Desktop", # (check your shortcut name)
}

# 2. Mappings for websites
WEBSITES = {
    'apple': 'https://www.apple.com',
    'microsoft': 'https://www.microsoft.com',
    'yahoo': 'https://www.yahoo.com',
    'bing': 'https://www.bing.com',
    'paypal': 'https://www.paypal.com',
    'ebay': 'https://www.ebay.com',
    'walmart': 'https://www.walmart.com',
    'target': 'https://www.target.com',
    'craigslist': 'https://www.craigslist.org',
    'pinterest': 'https://www.pinterest.com',
    'hulu': 'https://www.hulu.com',
    'pandora': 'https://www.pandora.com',
    'wordpress': 'https://www.wordpress.org',
    'quora': 'https://www.quora.com',
    'espn': 'https://www.espn.com',
    'nba': 'https://www.nba.com',
    'nfl': 'https://www.nfl.com',
    'mlb': 'https://www.mlb.com',
    'nationalgeographic': 'https://www.nationalgeographic.com',
    'weather': 'https://www.weather.com',
    'tripadvisor': 'https://www.tripadvisor.com',
    'yelp': 'https://www.yelp.com',
    'imdb': 'https://www.imdb.com',
    'buzzfeed': 'https://www.buzzfeed.com',
    'forbes': 'https://www.forbes.com',
    'cnbc': 'https://www.cnbc.com',
    'businessinsider': 'https://www.businessinsider.com',
    'nasa': 'https://www.nasa.gov',
    'ted': 'https://www.ted.com',
    'spotify': 'https://www.spotify.com',
    'hackernews': 'https://news.ycombinator.com',
    'dribbble': 'https://www.dribbble.com',
    'behance': 'https://www.behance.net',
    'adobe': 'https://www.adobe.com',
    'ubuntu': 'https://www.ubuntu.com',
    'docker': 'https://www.docker.com',
    'raspberrypi': 'https://www.raspberrypi.org',
    'arstechnica': 'https://arstechnica.com',
    'techcrunch': 'https://techcrunch.com',
    'cnet': 'https://www.cnet.com',
    'engadget': 'https://www.engadget.com',
    'gizmodo': 'https://gizmodo.com',
    'lifehacker': 'https://lifehacker.com',
    'webmd': 'https://www.webmd.com',
    'mayoclinic': 'https://www.mayoclinic.org',
    'nih': 'https://www.nih.gov',
    'harvard': 'https://www.harvard.edu',
    'mit': 'https://web.mit.edu',
    'stanford': 'https://www.stanford.edu',
    'coursera': 'https://www.coursera.org',
    'udacity': 'https://www.udacity.com',
    'edx': 'https://www.edx.org',
    'khanacademy': 'https://www.khanacademy.org',
    'codecademy': 'https://www.codecademy.com',
    'stackoverflow': 'https://stackoverflow.com',
    'gitlab': 'https://www.gitlab.com',
    'bitbucket': 'https://bitbucket.org',
    'digg': 'https://digg.com',
    'slashdot': 'https://slashdot.org',
    'medium': 'https://medium.com',
    'mashable': 'https://mashable.com',
    'wired': 'https://www.wired.com',
    'bbcnews': 'https://www.bbc.co.uk/news',
    'aljazeera': 'https://www.aljazeera.com',
    'reuters': 'https://www.reuters.com',
    'npr': 'https://www.npr.org',
    'nytimes': 'https://www.nytimes.com',
    'washingtonpost': 'https://www.washingtonpost.com',
    'theguardian': 'https://www.theguardian.com',
    'latimes': 'https://www.latimes.com',
    'usatoday': 'https://www.usatoday.com',
    'time': 'https://time.com',
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'tumblr': 'https://www.tumblr.com',
    'snapchat': 'https://www.snapchat.com',
    'whatsapp': 'https://www.whatsapp.com',
    'telegram': 'https://telegram.org',
    'youtube': 'https://www.youtube.com',
    'vimeo': 'https://vimeo.com',
    'twitch': 'https://www.twitch.tv',
    'soundcloud': 'https://soundcloud.com',
    'myspace': 'https://myspace.com',
    'flickr': 'https://www.flickr.com',
    'vine': 'https://vine.co',
    'periscope': 'https://www.pscp.tv',
    'mix': 'https://mix.com',
    'meetup': 'https://www.meetup.com',
    'badoo': 'https://badoo.com',
    'okcupid': 'https://www.okcupid.com',
    'tinder': 'https://tinder.com',
    'grindr': 'https://www.grindr.com',
    'hinge': 'https://hinge.co',
    'tagged': 'https://www.tagged.com',
    'hi5': 'https://hi5.com',
    'skout': 'https://www.skout.com',
    'friendster': 'https://www.friendster.com',
    'orcutt': 'https://orcutt.com',
    'xanga': 'https://www.xanga.com',
    'bebo': 'https://bebo.com',
    'plaxo': 'https://www.plaxo.com',
    'sonico': 'https://www.sonico.com',
    'moco': 'https://www.mocospace.com',
    'blued': 'https://www.blued.com',
    'weibo': 'https://www.weibo.com',
    'qq': 'https://www.qq.com',
    'douban': 'https://www.douban.com',
    'cyworld': 'https://www.cyworld.com',
    'mixi': 'https://mixi.jp',
    'renren': 'https://www.renren.com',
    'hyves': 'https://hyves.nl',
    'foursquare': 'https://foursquare.com',
    'swarm': 'https://www.swarmapp.com',
    'untappd': 'https://untappd.com',
    'goodreads': 'https://www.goodreads.com',
    'lastfm': 'https://www.last.fm',
    'delicious': 'https://del.icio.us',
    'stumbleupon': 'https://www.stumbleupon.com',
    'diigo': 'https://www.diigo.com',
    'newsvine': 'https://www.newsvine.com',
    'folkd': 'https://www.folkd.com',
    'scoop.it': 'https://www.scoop.it',
    'pearltrees': 'https://www.pearltrees.com',
    'dzone': 'https://dzone.com',
    'reddit': 'https://www.reddit.com',
    'hubpages': 'https://hubpages.com',
    'livejournal': 'https://www.livejournal.com',
    'bloglovin': 'https://www.bloglovin.com',
    'blogger': 'https://www.blogger.com',
    'taringa': 'https://www.taringa.net',
    'skyrock': 'https://www.skyrock.com',
    'twoo': 'https://www.twoo.com',
    'viadeo': 'https://www.viadeo.com',
    'diaspora': 'https://diasporafoundation.org',
    'ello': 'https://ello.co',
    'mastodon': 'https://joinmastodon.org',
    'meowchat': 'https://www.meowchat.com',
    'google': 'https://www.google.com',
    'w3schools': 'https://www.w3schools.com',
    'canva': 'https://www.canva.com',
    'youtubestudio': 'https://studio.youtube.com',
    'github': 'https://www.github.com',
    'udemy': 'https://www.udemy.com',
    'hackerrank': 'https://www.hackerrank.com',
    'codepen': 'https://codepen.io',
    'slack': 'https://slack.com',
    'zoom': 'https://zoom.us',
    'amazon': 'https://www.amazon.com',
    'netflix': 'https://www.netflix.com',
    'stackexchange': 'https://stackexchange.com',
    'cnn': 'https://www.cnn.com',
    'ubereats': 'https://www.ubereats.com',
    'doordash': 'https://www.doordash.com',
    'postmates': 'https://www.postmates.com',
    'grubhub': 'https://www.grubhub.com',
    'instacart': 'https://www.instacart.com',
    'booking': 'https://www.booking.com',
    'expedia': 'https://www.expedia.com',
    'airbnb': 'https://www.airbnb.com',
    'zillow': 'https://www.zillow.com',
    'realtor': 'https://www.realtor.com',
    'cars': 'https://www.cars.com',
    'autotrader': 'https://www.autotrader.com',
    'edmunds': 'https://www.edmunds.com',
    'kelleybluebook': 'https://www.kbb.com',
    'carmax': 'https://www.carmax.com',
    'chatgpt': 'https://chat.openai.com/'
}