"""
JARVIS NLU Training Data (Brain 1)
Author: Shivang Rastogi
Description: Master training templates for all intents and entities.
Language: Multilingual (English, Hindi, Hinglish)
"""

INTENT_TEMPLATES = {
    "greet": [
        ("hello", {}),
        ("hi", {}),
        ("hey jarvis", {}),
        ("good morning", {}),
        ("good evening", {}),
        ("good night", {}),
        ("howdy", {}),
        ("hey buddy", {}),
        ("hi there", {}),
        ("hello there", {}),
        ("hey assistant", {}),
        ("yo jarvis", {}),
        ("what’s up", {}),
        ("hey, how are you", {}),
        ("greetings", {}),
        ("morning!", {}),
        ("hey pal", {}),
        ("hello friend", {}),
        ("nice to see you", {}),
        ("long time no see", {}),
        ("नमस्ते", {}),
        ("कैसे हो", {}),
        ("सुप्रभात", {}),
        ("शुभ संध्या", {}),
        ("क्या हाल है", {}),
        ("नमस्कार", {}),
        ("हाय जार्विस", {}),
        ("कैसे चल रहा है", {}),
        ("अरे जार्विस", {}),
        ("आप कैसे हैं", {}),
        ("hey bro kya haal", {}),
        ("yo kya chal raha hai", {}),
        ("hi jarvis kaise ho", {}),
        ("hello yaar", {}),
        ("namaste jarvis", {}),
        ("morning ho gayi", {}),
        ("hey there buddy", {}),
        ("sup jarvis", {}),
        ("hey dost", {}),
        ("jarvis sun rahe ho", {}),
        ("hello machine", {}),
        ("hi smartie", {}),
        ("hey genius", {}),
        ("gud morning", {}),
        ("hey champ", {}),
        ("good afternoon", {}),
        ("namaste dost", {}),
        ("kya scene hai jarvis", {}),
        ("hi boss", {}),
        ("hey friend", {}),
        ("greetings to you", {}),
        ("yo kya bolti public", {}),
        ("a very good morning", {}),
        ("hello my friend", {}),
        ("hi sunshine", {}),
        ("jarvis are you there", {}),
        ("जार्विस, नमस्ते", {}),
        ("सुनो जार्विस", {}),
        ("कैसे हैं आप", {}),
        ("मिलकर खुशी हुई", {}),
        ("क्या हाल चाल", {}),
        ("जार्विस भाई", {}),
        ("good day", {}),
        ("what’s going on", {}),
        ("good to see you", {}),
        ("yo yo jarvis", {}),
        ("hello machine buddy", {}),
        ("hi genius bot", {}),
        ("hey superstar", {}),
        ("morning sunshine", {}),
        ("kya hal chal mere dost", {}),
        ("namaste bhai", {}),
        ("hi bro", {}),
        ("hi jarvisss", {}),
        ("are you awake", {}),
        ("jarvis, you online?", {}),
        ("hello computer", {}),
        ("gud eve", {}),
        ("hey dear", {}),
        ("hello system", {}),
        ("hi bhai", {}),
        ("namaste bhaiya", {}),
        ("suprabhat", {}),
        ("good noon", {}),
        ("hey robo", {}),
        ("jarvis zinda ho?", {}),
        ("kya haal hai", {}),
        ("namaskar", {}),
        ("what’s new", {}),
        ("good to hear you", {}),
        ("hey genius bot", {}),
        ("hi lovely jarvis", {}),
        ("hello master", {}),
        ("sup genius", {}),
        ("yo assistant", {}),
        ("good day jarvis", {}),
        ("अरे भाई, नमस्ते", {}),
        ("शुभ रात्रि", {}),
        ("सुप्रभात जार्विस", {}),
        ("जार्विस जी", {}),
        ("क्या हाल चाल भाई", {}),
        ("नमस्कार मित्र", {}),
        ("क्या बात है", {}),
        ("अरे यार जार्विस", {}),
        ("hey robo bro", {}),
        ("hi genius assistant", {}),
        ("hello legend", {}),
        ("good vibes only", {}),
        ("gud morning bro", {}),
        ("hey cool jarvis", {}),
        ("morning robot", {}),
        ("jarvis bhai kya hal", {}),
        ("hello meri jaan", {}),
        ("kya chal raha hai", {}),
        ("aaj mood kaisa hai", {}),
    ],
    "goodbye": [
        ("bye", {}),
        ("goodbye", {}),
        ("see you later", {}),
        ("see ya", {}),
        ("talk to you soon", {}),
        ("catch you later", {}),
        ("I’m off", {}),
        ("gotta go", {}),
        ("see you tomorrow", {}),
        ("take care", {}),
        ("farewell", {}),
        ("until next time", {}),
        ("peace out", {}),
        ("later bro", {}),
        ("see you soon", {}),
        ("bye bye", {}),
        ("okay bye", {}),
        ("good night", {}),
        ("good evening, bye", {}),
        ("ok, see ya", {}),
        ("अलविदा", {}),
        ("बाद में मिलते हैं", {}),
        ("फिर मिलेंगे", {}),
        ("फिर बात करेंगे", {}),
        ("चलता हूँ", {}),
        ("ठीक है, बाय", {}),
        ("अच्छा, फिर मिलते हैं", {}),
        ("फिर मिलते हैं दोस्त", {}),
        ("अच्छा, चलता हूँ", {}),
        ("मिलते रहेंगे", {}),
        ("bye jarvis", {}),
        ("see ya later bro", {}),
        ("chal milte hain", {}),
        ("ok tata", {}),
        ("alvida dost", {}),
        ("fir milte hai", {}),
        ("ok bye buddy", {}),
        ("chalo fir", {}),
        ("take care jarvis", {}),
        ("bye robot", {}),
        ("goodbye assistant", {}),
        ("ok bro bye", {}),
        ("ok cya", {}),
        ("milte hai baad me", {}),
        ("alvida jarvis", {}),
        ("phir milte hai", {}),
        ("bye bhai", {}),
        ("chal bye", {}),
        ("okay, I’m leaving", {}),
        ("see you next time", {}),
        ("talk soon", {}),
        ("good night jarvis", {}),
        ("sweet dreams", {}),
        ("jarvis bye", {}),
        ("alvida mere dost", {}),
        ("फिर मिलेंगे जार्विस", {}),
        ("अच्छा चलता हूँ भाई", {}),
        ("फिर बात करेंगे", {}),
        ("बाद में मिलते हैं दोस्त", {}),
        ("ठीक है, मिलता हूँ", {}),
        ("फिर मुलाकात होगी", {}),
        ("चलो अलविदा", {}),
        ("ठीक है फिर", {}),
        ("अच्छा बाय", {}),
        ("okay see ya", {}),
        ("bye for now", {}),
        ("tata bye bye", {}),
        ("take care buddy", {}),
        ("later assistant", {}),
        ("chal fir bro", {}),
        ("ok milte hai", {}),
        ("bye yaar", {}),
        ("goodbye friend", {}),
        ("farewell my assistant", {}),
        ("good night and bye", {}),
        ("see ya next time", {}),
        ("bye my bro", {}),
        ("ok going offline", {}),
        ("catch you later jarvis", {}),
        ("good night dear", {}),
        ("bye genius", {}),
        ("phir baat karte hai", {}),
        ("goodbye master", {}),
        ("okay jarvis see you", {}),
        ("phir milte hain bro", {}),
        ("bye robo", {}),
        ("see you soon robot", {}),
        ("bye meri jaan", {}),
        ("chalo milte hai", {}),
        ("bye take care", {}),
        ("milte rahenge", {}),
        ("tata jarvis", {}),
        ("okay cya later", {}),
        ("good night dost", {}),
        ("see ya robo", {}),
        ("ok done bye", {}),
        ("chal phir milte hain", {}),
        ("bye khyal rakhna", {}),
        ("फिर मिलते हैं यार", {}),
        ("ठीक है, शुभ रात्रि", {}),
        ("चलते हैं", {}),
        ("फिर बात करेंगे दोस्त", {}),
        ("अच्छा भाई, चलता हूँ", {}),
    ],
    "check_time": [
        ("what time is it", {}),
        ("can you tell me the time", {}),
        ("tell me the time", {}),
        ("what’s the time now", {}),
        ("current time please", {}),
        ("give me the time", {}),
        ("what time right now", {}),
        ("abhi time kya hua hai", {}),
        ("samay kya hua hai", {}),
        ("abhi kitne baje hain", {}),
        ("samay batao", {}),
        ("kitna time hua", {}),
        ("please tell the time", {}),
        ("show me current time", {}),
        ("what’s the local time", {}),
        ("[Tokyo](location) mein kya time hai", {}),
        ("what’s the time in [London](location)", {}),
        ("[New York](location) ka samay kya hai", {}),
        ("tell me time in [Delhi](location)", {}),
        ("[Mumbai](location) mein time batao", {}),
        ("[Bangalore](location) ka time kya hai", {}),
        ("what’s the time there", {}),
        ("tell me current time in [Paris](location)", {}),
        ("show me time in [Noida](location)", {}),
        ("[Pune](location) mein kitne baje hain", {}),
        ("samay bataiye", {}),
        ("abhi ka samay kya hai", {}),
        ("jarvis tell me the time", {}),
        ("what time in [Dubai](location)", {}),
        ("[Hyderabad](location) mein kya time hua", {}),
        ("show me [Los Angeles](location) time", {}),
        ("tell me [Kolkata](location) time", {}),
        ("[Sydney](location) ka time kya hai", {}),
        ("what time in [Berlin](location)", {}),
        ("[Chennai](location) mein samay kya hai", {}),
        ("[Tokyo](location) ka samay batao", {}),
        ("abhi kitne baje ho rahe hain", {}),
        ("time dikhao", {}),
        ("current samay batao", {}),
        ("what time is it right now", {}),
        ("tell me the exact time", {}),
        ("kitna time ho gaya", {}),
        ("jarvis, kya time hua", {}),
        ("abhi kya time hai", {}),
        ("can you show me the time", {}),
        ("aaj ka time batao", {}),
        ("right now time kya hai", {}),
        ("samay kya chal raha hai", {}),
        ("show current clock", {}),
        ("display time please", {}),
        ("abhi ka samay kya chal raha", {}),
        ("jarvis time bolo", {}),
        ("abhi time dikhao", {}),
        ("kitne baje hue hain", {}),
        ("show me the world clock", {}),
        ("what’s the time difference", {}),
        ("samay bataiye zara", {}),
        ("abhi ke time batao", {}),
        ("time now", {}),
        ("abhi time", {}),
        ("current clock please", {}),
        ("[Delhi](location) mein samay kya hai", {}),
        ("[Lucknow](location) ka time kya hai", {}),
        ("[Jaipur](location) mein kitne baje hain", {}),
        ("abhi ka current time", {}),
        ("right now kya time hua", {}),
        ("[Canada](location) ka time batao", {}),
        ("[Germany](location) mein kya time hua", {}),
        ("[America](location) ka time kya hai", {}),
        ("[Nepal](location) ka samay kya hai", {}),
        ("[Pakistan](location) mein kya time hai", {}),
        ("samay kya ho raha hai", {}),
        ("tell time quickly", {}),
        ("give me clock info", {}),
        ("samay dikhao", {}),
        ("abhi ka samay kya ho raha", {}),
        ("abhi ke time kaun sa hai", {}),
        ("show clock", {}),
        ("current time in [Singapore](location)", {}),
        ("abhi [Goa](location) mein time kya hai", {}),
        ("[London](location) ka time kya hai", {}),
        ("[Tokyo](location) ka current time", {}),
        ("[Paris](location) time please", {}),
        ("tell me global time", {}),
        ("abhi ka clock dikhaiye", {}),
        ("please tell time", {}),
        ("jarvis samay batao", {}),
        ("what’s India’s time", {}),
        ("Indian time please", {}),
        ("bharat ka samay kya hai", {}),
        ("samay kya bataoge", {}),
        ("abhi kya baje hain", {}),
        ("samay kitna hua", {}),
        ("abhi time kya ho gaya", {}),
        ("jarvis kitne baje hain", {}),
        ("current India time", {}),
        ("aaj ka samay batao", {}),
        ("clock khol do", {}),
        ("[Tokyo](location) ka local time", {}),
        ("[New Delhi](location) ka time kya hai", {}),
        ("[Kolkata](location) time now", {}),
        ("what is clock time", {}),
        ("display current time", {}),
        ("abhi ke time dikhao", {}),
        ("kitne baje hue", {}),
        ("[London](location) time now", {}),
    ],
    "check_weather": [
        ("what's the weather like", {}),
        ("what's the weather today", {}),
        ("how's the weather", {}),
        ("tell me the weather", {}),
        ("is it raining right now", {}),
        ("will it rain today", {}),
        ("is it sunny outside", {}),
        ("do I need an umbrella", {}),
        ("weather forecast please", {}),
        ("give me the weather report", {}),
        ("current weather update", {}),
        ("how's the weather in [Mumbai](location)", {}),
        ("aaj ka mausam kaisa hai", {}),
        ("aaj baarish hogi kya", {}),
        ("aaj dhoop hai kya", {}),
        ("aaj ka weather batao", {}),
        ("[Delhi](location) ka mausam batao", {}),
        ("temperature kya hai", {}),
        ("current temperature please", {}),
        ("today's weather", {}),
        ("aaj mausam bata do jarvis", {}),
        ("is it windy outside", {}),
        ("kya bahut thand hai", {}),
        ("how hot is it", {}),
        ("how cold is it", {}),
        ("what's the temperature in [Pune](location)", {}),
        ("weather in [Bangalore](location) right now", {}),
        ("aaj [Noida](location) mein mausam kaisa hai", {}),
        ("weather forecast for [Hyderabad](location)", {}),
        ("is it snowing in [Delhi](location)", {}),
        ("kya aaj tufan aayega", {}),
        ("humidity kitna hai", {}),
        ("air quality kaisa hai", {}),
        ("AQI batao", {}),
        ("air quality index check karo", {}),
        ("UV index batao", {}),
        ("sunrise time kya hai", {}),
        ("sunset time batao", {}),
        ("will it be sunny tomorrow", {}),
        ("kal mausam kaisa hoga", {}),
        ("tomorrow's weather please", {}),
        ("show weekly forecast", {}),
        ("show 7 day forecast", {}),
        ("7 day weather forecast", {}),
        ("what's the forecast this week", {}),
        ("is there a storm warning", {}),
        ("storm alert check karo", {}),
        ("thunderstorm probability kya hai", {}),
        ("hail aane ka chance hai?", {}),
        ("how much chance of rain", {}),
        ("rain probability batao", {}),
        ("chance of rain today", {}),
        ("kya aaj bijli girne ka khatra hai", {}),
        ("is it humid today", {}),
        ("kya aaj garmi zyada hogi", {}),
        ("temperature forecast for [Chennai](location)", {}),
        ("is it chilly outside", {}),
        ("it feels cold outside", {}),
        ("how's the weather outside", {}),
        ("open weather app", {}),
        ("give me weather for [Los Angeles](location)", {}),
        ("[London](location) ka mausam batao", {}),
        ("how's the sky right now", {}),
        ("is it cloudy", {}),
        ("cloud cover batao", {}),
        ("visibility kitni hai", {}),
        ("is there fog today", {}),
        ("fog warning hai kya", {}),
        ("air pressure batao", {}),
        ("barometer reading do", {}),
        ("dew point kya hai", {}),
        ("weather alert notify karo", {}),
        ("notify me about severe weather", {}),
        ("set weather alerts", {}),
        ("kya mausam theek rahega aaj", {}),
        ("pack an umbrella?", {}),
        ("umbrella laana padega kya", {}),
        ("do I need a jacket", {}),
        ("kya jacket pehenna chahiye", {}),
        ("how's the weather in [Kolkata](location)", {}),
        ("temperature in [Singapore](location) batao", {}),
        ("weather update in [Tokyo](location) now", {}),
        ("[Pune](location) ke liye forecast dekhao", {}),
        ("aaj ke liye weather alert bhejo", {}),
        ("is there a heatwave warning", {}),
        ("heatwave warning hai kya", {}),
        ("cold wave chance kya hai", {}),
        ("[Patna](location) ka temperature batao", {}),
        ("check weather radar", {}),
        ("show precipitation radar", {}),
        ("check satellite view", {}),
        ("show cloud map", {}),
        ("storm ki update do", {}),
        ("kya aaj baarish zyada hogi", {}),
        ("is it drizzling", {}),
        ("light rain ho rahi hai kya", {}),
        ("moderate rain ho rahi hai kya", {}),
        ("heavy rain hai kya", {}),
        ("torrential rain ka chance hai", {}),
        ("hail storm hai kya", {}),
        ("kya bijli chamkega", {}),
        ("kya tufan aayega", {}),
        ("will there be thunderstorms", {}),
        ("thunderstorm aane wala hai kya", {}),
        ("aaj ka mausam kaisa lagega", {}),
        ("what's the weather right now in [Berlin](location)", {}),
        ("[Toronto](location) weather please", {}),
        ("kya mausam thik rahega weekend par", {}),
        ("weekend weather batao", {}),
        ("is it safe to travel because of weather", {}),
        ("travel advisory for weather", {}),
        ("will the rain stop soon", {}),
        ("kab baarish rukegi", {}),
        ("sunrise & sunset time batao", {}),
        ("aaj subah kitne baje suraj nikla", {}),
        ("sunrise time in [Goa](location)", {}),
        ("sunset time in [Ahmedabad](location)", {}),
        ("how's the temperature now", {}),
        ("kya hawa tez chal rahi hai", {}),
        ("wind speed batao", {}),
        ("gust speed kya hai", {}),
        ("is dew heavy today", {}),
        ("is the pollen count high", {}),
        ("pollen count batao", {}),
        ("allergy index check karo", {}),
        ("weather kab change hoga", {}),
        ("when will the weather change", {}),
        ("alert me if it rains tonight", {}),
        ("notify if rain starts", {}),
        ("send me weather warnings", {}),
        ("mausam ki warning bhej do", {}),
        ("please update me about weather", {}),
        ("daily weather update set karo", {}),
        ("set daily weather briefing", {}),
        ("morning weather briefing please", {}),
        ("breakfast time weather batao", {}),
        ("evening weather kya hoga", {}),
        ("night weather report dekhao", {}),
        ("aaj raat mausam kaisa hoga", {}),
        ("is there a tornado watch", {}),
        ("tornado warning hai kya", {}),
        ("earthquake aur weather ka relation batao", {}),
        # This is the bug fix from our test
        ("[पुणे](location) का मौसम बताओ", {}),
    ],
    "open_software": [
        ("open [chrome](app_name)", {}),
        ("launch [Visual Studio Code](app_name)", {}),
        ("start [Edge](app_name)", {}),
        ("open [notepad](app_name)", {}),
        ("open [calculator](app_name)", {}),
        ("open [Spotify](app_name)", {}),
        ("launch [Slack](app_name)", {}),
        ("start [Zoom](app_name)", {}),
        ("open [Photoshop](app_name)", {}),
        ("open the [Terminal](app_name)", {}),
        ("open my [browser](app_name)", {}),
        ("launch the [Email](app_name) app", {}),
        ("[youtube](app_name) खोलो", {}),
        ("[VLC](app_name) chalao", {}),
        ("open [Calculator](app_name) please", {}),
        ("start [Word](app_name)", {}),
        ("launch [Excel](app_name)", {}),
        ("open [PowerPoint](app_name)", {}),
        ("open [Calendar](app_name)", {}),
        ("open [Terminal](app_name) for me", {}),
        ("open my [music player](app_name)", {}),
        ("launch [Photos](app_name)", {}),
        ("start [CMD](app_name)", {}),
        ("open [Sublime Text](app_name)", {}),
        ("launch [PyCharm](app_name)", {}),
        ("open [IntelliJ IDEA](app_name)", {}),
        ("open [Notion](app_name)", {}),
        ("open [Discord](app_name)", {}),
        ("open code editor", {}),
        ("launch my IDE", {}),
        ("start the IDE", {}),
        ("open browser", {}),
        ("open email client", {}),
        ("open file explorer", {}),
        ("open explorer", {}),
        ("open [FileZilla](app_name)", {}),
        ("launch [OBS Studio](app_name)", {}),
        ("open [Blender](app_name)", {}),
        ("open [Photoshop CC](app_name)", {}),
        ("open [Edge](app_name) window", {}),
        ("open [Google Chrome](app_name)", {}),
        ("open [Brave](app_name)", {}),
        ("open [Opera](app_name)", {}),
        ("open [Tor Browser](app_name)", {}),
        ("open [Vivaldi](app_name)", {}),
        ("open [Edge Canary](app_name)", {}),
        ("launch my [notes app](app_name)", {}),
        ("open [Evernote](app_name)", {}),
        ("start [OneNote](app_name)", {}),
        ("open [Terminal](app_name) and run command", {}),
        ("open the [camera](app_name)", {}),
        ("launch camera app", {}),
        ("open [Weather](app_name) app", {}),
        ("open [Maps](app_name)", {}),
        ("open [Google Maps](app_name)", {}),
        ("launch the music app", {}),
        ("open [iTunes](app_name)", {}),
        ("start [Spotify](app_name) and play music", {}),
        ("open [VS Code](app_name)", {}),
        ("open [GIMP](app_name)", {}),
        ("open [Paint](app_name)", {}),
        ("open [Calculator](app_name) and add 2+2", {}),
        ("open [System Settings](app_name)", {}),
        ("show me [Control Panel](app_name)", {}),
        ("open [Task Manager](app_name)", {}),
        ("start [Task Manager](app_name)", {}),
        ("open [Settings](app_name)", {}),
        ("open [Paint.NET](app_name)", {}),
        ("open [Notepad++](app_name)", {}),
        ("open [Adobe Reader](app_name)", {}),
        ("launch [Foxit Reader](app_name)", {}),
        ("open [Slack](app_name) and show channels", {}),
        ("open [Telegram](app_name)", {}),
        ("open [WhatsApp Desktop](app_name)", {}),
        ("open whatsapp", {}),
        ("open outlook", {}),
        ("start outlook app", {}),
        ("open gmail in browser", {}),
        ("open youtube in browser", {}),
        ("open [Adobe Premiere Pro](app_name)", {}),
        ("launch [After Effects](app_name)", {}),
        ("open [Steam](app_name)", {}),
        ("start [Epic Games Launcher](app_name)", {}),
        ("open [Minecraft](app_name)", {}),
        ("open [Spotify](app_name) playlist", {}),
        ("open [Zoom](app_name) meeting", {}),
        ("open a new browser window", {}),
        ("open incognito window", {}),
        ("launch browser in private mode", {}),
        ("open the downloads folder", {}),
        ("open recent files", {}),
        ("open last opened file", {}),
        ("open my project in [VS Code](app_name)", {}),
        ("open my code editor", {}),
        ("launch the text editor", {}),
        ("open [Brackets](app_name)", {}),
        ("start [Atom](app_name)", {}),
        ("open [Android Studio](app_name)", {}),
        ("open [Xcode](app_name)", {}),
        ("launch [Docker Desktop](app_name)", {}),
        ("open [Postman](app_name)", {}),
        ("start [Tableau](app_name)", {}),
        ("open [Power BI](app_name)", {}),
        ("open [Sublime](app_name) project", {}),
        ("open [File Manager](app_name)", {}),
        ("start [Terminal](app_name) as admin", {}),
        ("open app store", {}),
        ("open microsoft store", {}),
        ("open gadget manager", {}),
        ("open device manager", {}),
        ("open Control Panel", {}),
        ("open task manager please", {}),
        ("launch [Calendar](app_name) app", {}),
        ("open [Reminders](app_name)", {}),
        ("open [Calculator](app_name) on desktop", {}),
        ("open [Dictionary](app_name)", {}),
        ("open [Translate](app_name)", {}),
        ("open [Maps](app_name) and show route", {}),
    ],
    "search_youtube": [
        ("search youtube for [latest movie trailers](search_query)", {}),
        ("on youtube, find [python tutorials](search_query)", {}),
        ("youtube par [new songs](search_query) search karo", {}),
        ("यूट्यूब पर [कैसे करें](search_query) खोजें", {}),
        ("search youtube for [music videos](search_query)", {}),
        ("youtube me [cute cat videos](search_query) dhoondo", {}),
        ("find [kitchen recipes](search_query) on youtube", {}),
        ("youtube par [workout videos](search_query) dikhao", {}),
        ("search for [lofi hiphop beats](search_query) on youtube", {}),
        ("play [lofi beats](search_query) on youtube", {}),
        ("search youtube for [news highlights](search_query)", {}),
        ("find [coding interviews](search_query) on youtube", {}),
        ("youtube me [react tutorial](search_query) search karo", {}),
        ("search youtube for [Hindi songs 2025](search_query)", {}),
        ("find [stand-up comedy](search_query) on youtube", {}),
        ("youtube par [travel vlogs](search_query) dikhao", {}),
        ("search for [product reviews](search_query) on youtube", {}),
        ("play [motivation speech](search_query) on youtube", {}),
        ("search youtube for [chess games](search_query)", {}),
        ("find [physics lectures](search_query) on youtube", {}),
        ("youtube se [old bollywood songs](search_query) nikaalo", {}),
        ("search youtube for [guitar lessons](search_query)", {}),
        ("youtube par [study music](search_query) play karo", {}),
        ("search [asmr videos](search_query) on youtube", {}),
        ("find [documentary about space](search_query) on youtube", {}),
        ("search youtube for [movie trailers 2025](search_query)", {}),
        ("youtube me [meditation music](search_query) dhoondo", {}),
        ("search for [news bulletin](search_query) on youtube", {}),
        ("find [code along tutorial](search_query) on youtube", {}),
        ("search youtube for [cooking hacks](search_query)", {}),
        ("play [Bollywood hits](search_query) on youtube", {}),
        ("search youtube for [java tutorials](search_query)", {}),
        ("youtube par [naqshbandi qawwalis](search_query) khojo", {}),
        ("find [short films](search_query) on youtube", {}),
        ("search youtube for [science experiments](search_query)", {}),
        ("youtube me [draw with me](search_query) dhoondo", {}),
        ("search for [k-pop performances](search_query) on youtube", {}),
        ("find [gaming highlights](search_query) on youtube", {}),
        ("search youtube for [coding playlist](search_query)", {}),
        ("youtube par [Bollywood dance](search_query) dikhao", {}),
        ("search youtube for [interview tips](search_query)", {}),
        ("find [gadget reviews](search_query) on youtube", {}),
        ("search for [shorts about cooking](search_query) on youtube", {}),
        ("play [news live stream](search_query) on youtube", {}),
        ("youtube me [bhajan songs](search_query) play karo", {}),
        ("search youtube for [science channels](search_query)", {}),
        ("find [makeup tutorials](search_query) on youtube", {}),
        ("search youtube for [how to tie a tie](search_query)", {}),
        ("youtube par [gaming walkthroughs](search_query) dhoondo", {}),
        ("search for [home workout routine](search_query) on youtube", {}),
        ("find [best of classical music](search_query) on youtube", {}),
        ("search youtube for [full movies in Hindi](search_query)", {}),
        ("play [TED talk](search_query) on youtube", {}),
        ("search youtube for [history documentaries](search_query)", {}),
        ("youtube pe [tutorials for beginners](search_query) dhoondo", {}),
        ("search youtube for [funny cat compilations](search_query)", {}),
        ("find [how to fix bike](search_query) on youtube", {}),
        ("search youtube for [startup pitch decks](search_query)", {}),
        ("youtube par [travel tips india](search_query) search karo", {}),
        ("search youtube for [live concerts](search_query)", {}),
        ("find [documentary on wildlife](search_query) on youtube", {}),
        ("search for [season highlights lakers](search_query) on youtube", {}),
        ("play [instrumental piano](search_query) on youtube", {}),
        ("search youtube for [gardening tips](search_query)", {}),
        ("find [product unboxing](search_query) on youtube", {}),
        ("search youtube for [python asyncio tutorial](search_query)", {}),
        ("youtube par [cooking shows](search_query) nikal do", {}),
        ("search youtube for [data science playlist](search_query)", {}),
        ("play [live cricket match](search_query) on youtube", {}),
        ("search youtube for [film analysis](search_query)", {}),
        ("find [coding interview questions](search_query) on youtube", {}),
        ("youtube me [icons designer tutorial](search_query) dhoondo", {}),
        ("search youtube for [dance choreography](search_query)", {}),
        ("find [fitness motivation](search_query) on youtube", {}),
        ("search youtube for [js conf talks](search_query)", {}),
        ("play [classical guitar](search_query) on youtube", {}),
        ("find [anime openings](search_query) on youtube", {}),
        ("search youtube for [productivity tips](search_query)", {}),
        ("youtube me [short comedy skits](search_query) dhoondo", {}),
        ("search for [programming livestreams](search_query) on youtube", {}),
        ("find [how to build apps](search_query) on youtube", {}),
        ("search youtube for [mock interviews](search_query)", {}),
        ("play [relaxing rain sounds](search_query) on youtube", {}),
        ("search youtube for [speech & debate](search_query)", {}),
        ("find [Hindi standup 2024](search_query) on youtube", {}),
        ("youtube par [coding live streams](search_query) dikhao", {}),
        ("search youtube for [how to change a tire](search_query)", {}),
        ("play [motivational playlist](search_query) on youtube", {}),
        ("search youtube for [interview with CEO](search_query)", {}),
    ],
    "check_internet_speed": [
        ("what's my internet speed", {}),
        ("check internet speed", {}),
        ("run a speed test", {}),
        ("how fast is my connection", {}),
        ("test my internet speed", {}),
        ("measure my wifi speed", {}),
        ("speed test please", {}),
        ("how's my connection speed", {}),
        ("tell me my network speed", {}),
        ("show my bandwidth speed", {}),
        ("internet speed batao", {}),
        ("mera internet kitna fast hai", {}),
        ("speed test chalao", {}),
        ("wifi speed dikhao", {}),
        ("connection speed kaisi hai", {}),
        ("स्पीड टेस्ट करो", {}),
        ("इंटरनेट स्पीड बताओ", {}),
        ("मेरा इंटरनेट कैसा है", {}),
        ("वाईफाई स्पीड चेक करो", {}),
        ("नेटवर्क स्पीड दिखाओ", {}),
        ("check my jio speed", {}),
        ("run wifi test", {}),
        ("how fast is airtel today", {}),
        ("show my ping speed", {}),
        ("download speed batao", {}),
        ("upload speed test karo", {}),
        ("speed test run karo", {}),
        ("wifi test chalao", {}),
        ("tell me the mbps", {}),
        ("mera speed test result batao", {}),
        ("network test karo", {}),
        ("wifi speed check karo", {}),
        ("what’s my download rate", {}),
        ("upload speed kitni hai", {}),
        ("run an internet speed test", {}),
        ("jarvis, test the wifi", {}),
        ("connection check karo", {}),
        ("internet kitna slow hai", {}),
        ("wifi ka speed bata", {}),
        ("speed slow hai kya", {}),
        ("network test please", {}),
        ("speed verify karo", {}),
        ("mera network stable hai kya", {}),
        ("test karo connection ko", {}),
        ("kitna ping aa raha hai", {}),
        ("show speed graph", {}),
        ("run ookla test", {}),
        ("jarvis, check connection", {}),
        ("wifi bandwidth test karo", {}),
        ("meri speed slow lag rahi hai", {}),
        ("connection ka status batao", {}),
        ("check speed again", {}),
        ("retest internet", {}),
        ("wifi speed monitor karo", {}),
        ("network speed check kar do", {}),
        ("internet test kar do", {}),
        ("wifi ka result batao", {}),
        ("mera ping high hai kya", {}),
        ("run fast.com", {}),
        ("test karo bandwidth", {}),
        ("speed check karna hai", {}),
        ("wifi ka test chalao", {}),
        ("connection stable hai kya", {}),
        ("jarvis, check my net speed", {}),
        ("wifi kitna fast hai", {}),
        ("speed test abhi chalao", {}),
        ("wifi check karo", {}),
        ("speed badh rahi hai kya", {}),
        ("internet ka graph dikhao", {}),
        ("ping kitna aa raha hai", {}),
        ("run speed analysis", {}),
        ("wifi ka status batao", {}),
        ("mera net slow hai", {}),
        ("speed check please", {}),
        ("run internet test again", {}),
        ("meri bandwidth kitni hai", {}),
        ("net speed dikha do", {}),
        ("internet test kar lo", {}),
        ("wifi ka analysis karo", {}),
        ("mera net slow chal raha hai", {}),
        ("check my upload speed", {}),
        ("mera download speed check karo", {}),
        ("test my broadband", {}),
        ("wifi fast hai kya", {}),
        ("internet ka result batao", {}),
        ("speed check kar do", {}),
        ("ping test karo", {}),
        ("jarvis, speed test", {}),
        ("mera connection sahi hai kya", {}),
        ("wifi ka signal strong hai kya", {}),
        ("internet lag kar raha hai kya", {}),
        ("run speed meter", {}),
        ("meri speed ka report do", {}),
        ("connection test karo", {}),
        ("wifi speed dikhaiye", {}),
        ("mera internet test karo", {}),
        ("speed report batao", {}),
        ("wifi test abhi karo", {}),
        ("jarvis, check wifi", {}),
        ("mera internet kaisa hai", {}),
        ("network speed check now", {}),
        ("internet test result dikhaiye", {}),
        ("meri wifi ka test karo", {}),
        ("run my speed test", {}),
        ("show my connection report", {}),
    ],
    "ask_question": [
        ("what is [AI](query)", {}),
        ("who is [Shah Rukh Khan](query)", {}),
        ("tell me about [the taj mahal](query)", {}),
        ("[भारत](query) की राजधानी क्या है", {}),
        ("[कंप्यूटर](query) क्या है", {}),
        ("who invented [telephone](query)", {}),
        ("define [machine learning](query)", {}),
        ("explain [quantum computing](query)", {}),
        ("tell me who is [Elon Musk](query)", {}),
        ("where is [Mount Everest](query) located", {}),
        ("[दिल्ली](query) का मौसम कैसा है", {}),
        ("[मंगल ग्रह](query) की दूरी कितनी है", {}),
        ("what do you know about [python](query)", {}),
        ("when was [India](query) independent", {}),
        ("who discovered [gravity](query)", {}),
        ("[सूरज](query) कितना बड़ा है", {}),
        ("[समुद्र](query) की गहराई क्या है", {}),
        ("what does [AI](query) mean", {}),
        ("who is [Newton](query)", {}),
        ("how tall is [Burj Khalifa](query)", {}),
        ("jarvis, who is [Obama](query)", {}),
        ("[earth](query) ka size kya hai", {}),
        ("[moon](query) kis metal ka hai", {}),
        ("where is [Taj Mahal](query)", {}),
        ("who created [facebook](query)", {}),
        ("what is [chatgpt](query)", {}),
        ("[भारत](query) की खोज किसने की", {}),
        ("[NASA](query) क्या है", {}),
        ("[जुपिटर](query) ग्रह कैसा है", {}),
        ("who founded [Google](query)", {}),
        ("what does [CPU](query) stand for", {}),
        ("tell me about [India Gate](query)", {}),
        ("[जयपुर](query) किस राज्य में है", {}),
        ("[कोहिनूर](query) हीरा कहाँ है", {}),
        ("who is [APJ Abdul Kalam](query)", {}),
        ("[माउंट एवरेस्ट](query) की ऊँचाई क्या है", {}),
        ("[चाँद](query) पर पानी है क्या", {}),
        ("[नदी](query) कितनी लंबी होती है", {}),
        ("how old is [earth](query)", {}),
        ("who discovered [electricity](query)", {}),
        ("[AI](query) kya karta hai", {}),
        ("explain [blockchain](query)", {}),
        ("define [robotics](query)", {}),
        ("what is [climate change](query)", {}),
        ("[water](query) ka formula kya hai", {}),
        ("[sun](query) kitna bada hai", {}),
        ("who is [Virat Kohli](query)", {}),
        ("what is [ISRO](query)", {}),
        ("[rainbow](query) kaise banta hai", {}),
        ("tell me about [NASA](query)", {}),
        ("[volcano](query) kya hota hai", {}),
        ("[earthquake](query) ka reason kya hai", {}),
        ("[internet](query) kisne banaya", {}),
        ("who is [PM of India](query)", {}),
        ("[ocean](query) kitna deep hai", {}),
        ("what is [AI model](query)", {}),
        ("[virus](query) kya hota hai", {}),
        ("who wrote [Ramayana](query)", {}),
        ("[पृथ्वी](query) गोल क्यों है", {}),
        ("[समय](query) क्या है", {}),
        ("[firewall](query) ka use kya hai", {}),
    ],
    "chit_chat": [
        ("how are you", {}),
        ("what's up", {}),
        ("tell me a joke", {}),
        ("you are cool", {}),
        ("क्या चल रहा है", {}),
        ("मजे में?", {}),
        ("एक चुटकुला सुनाओ", {}),
        ("i’m fine", {}),
        ("feeling good today", {}),
        ("you’re funny", {}),
        ("mood kaisa hai", {}),
        ("क्या हाल है", {}),
        ("tum mast ho", {}),
        ("nice to talk", {}),
        ("happy to chat", {}),
        ("kaisa laga mera joke", {}),
        ("you’re amazing", {}),
        ("haan sab badhiya", {}),
        ("aaj mood sahi hai", {}),
        ("funny lag rahe ho", {}),
        ("tumhe kaam karna pasand hai", {}),
        ("jarvis, tell something fun", {}),
        ("make me laugh", {}),
        ("kuch interesting bolo", {}),
        ("are you busy", {}),
        ("mujhe bore mat karo", {}),
        ("kuch funny sunao", {}),
        ("do you sleep", {}),
        ("what do you like", {}),
        ("mujhe hasi chahiye", {}),
        ("are you happy", {}),
        ("tum kahan rehte ho", {}),
        ("are you robot", {}),
        ("acha lag raha hai baat karke", {}),
        ("you’re so kind", {}),
        ("tell me something cool", {}),
        ("jarvis, you rock", {}),
        ("batao joke", {}),
        ("you are nice", {}),
        ("you’re my friend", {}),
        ("tumhare jokes funny hai", {}),
        ("aaj kaise ho", {}),
        ("tumhe coffee pasand hai", {}),
        ("say something nice", {}),
        ("how do you feel", {}),
        ("i missed you jarvis", {}),
        ("kuch mazedar sunao", {}),
        ("tum smart ho", {}),
        ("batao ek funny line", {}),
        ("tumhara din kaisa tha", {}),
        ("you make me smile", {}),
        ("jarvis, entertain me", {}),
        ("tum kuch ga sakte ho", {}),
        ("you are best", {}),
        ("you’re intelligent", {}),
        ("hum dono best friend hai", {}),
        ("are you okay", {}),
        ("acha lagta hai tumse baat karke", {}),
        ("you’re cute", {}),
        ("tum so rahe the kya", {}),
        ("mujhe ek chutkula sunao", {}),
        ("you’re so funny", {}),
        ("tell me something random", {}),
        ("tumhare pas jokes hai kya", {}),
        ("aaj ka din kaisa tha", {}),
        ("you’re awesome", {}),
        ("mujhe ek story sunao", {}),
        ("how do you work", {}),
        ("you’re sweet", {}),
        ("tumko kisne banaya", {}),
        ("mujhe pyar se bulao", {}),
        ("you are my buddy", {}),
        ("kuch majaidar bolo", {}),
        ("you’re too good", {}),
        ("tum great ho", {}),
        ("jarvis, bolo kuch cool", {}),
        ("hum dost hai kya", {}),
        ("you talk nice", {}),
        ("tumhare pas talent hai", {}),
        ("make me smile", {}),
        ("you make jokes", {}),
        ("tum kuch funny kar sakte ho", {}),
        ("you are awesome, jarvis", {}),
        ("i like talking to you", {}),
        ("you are smart", {}),
        ("tumhara mood kaisa hai", {}),
        ("how are you feeling", {}),
        ("you’re so cool", {}),
        ("aaj kya soch rahe ho", {}),
        ("you’re always nice", {}),
        ("tum best ho", {}),
        ("you’re great company", {}),
        ("jarvis, you’re my bro", {}),
        ("tumhara naam accha hai", {}),
        ("you’re chill", {}),
        ("i enjoy chatting", {}),
        ("tum kuch dance karoge", {}),
        ("you are funny, jarvis", {}),
        ("tum amazing ho", {}),
    ],
    "add_google_calendar_event": [
        ("schedule a [team sync](title) for [tomorrow](date) at [4pm](start_time)", {}),
        ("add [Dentist Appointment](title) on [November 20th](date)", {}),
        ("book [Lunch with Mom](title) from [1pm](start_time) to [2pm](end_time) [today](date)", {}),
        ("[कल](date) [शाम 5 बजे](start_time) [मीटिंग](title) सेट करो", {}),
        ("[Doctor visit](title) book karo [parso](date) [11am](start_time) ka", {}),
        ("add a [meeting](title) for [this Friday](date)", {}),
        ("[Monday](date) [10am](start_time) [Code Review](title)", {})
    ],
    "play_youtube_song": [
        ("play [Uptown Funk](song_name)", {}),
        ("play [Bohemian Rhapsody](song_name) by [Queen](artist)", {}),
        ("I want to hear [The Weeknd](artist)", {}),
        ("put on some [classic rock](genre)", {}),
        ("[Arijit Singh](artist) ke gaane bajao", {}),
        ("[Tum Hi Ho](song_name) play karo", {})
    ]
}